import { build, type QuoteRows } from "./types";

/** English, part 1. Attributed only where the attribution is certain; everything else is unattributed. */
const ROWS: QuoteRows = {
  calm: [
    "Breathe in slowly. Nothing needs to be solved in this one breath.",
    "You don't have to hurry to be on time with your own life.",
    "A quiet mind is not an empty mind. It's one that has stopped shouting.",
    "Let the day be the size of the next hour.",
    "Slow is a speed too. It still gets you there.",
    "The water settles when you stop stirring it.",
    "Rest is not what you do after the work is done. It's part of the work.",
    "Not every thought deserves a reply.",
    "Come back to your breath. It never left.",
    "Be gentle with the pace you can manage today.",
    "Peace is often just one less thing carried at once.",
    "You are allowed to put it down for a while and pick it up later.",
    "A calm morning is built the night before, and forgiven the morning after.",
    "Let your shoulders drop. They've been up for hours.",
    "Some days the only task is to stay kind to yourself.",
    "Silence is also an answer, and often a good one.",
    ["We suffer more often in imagination than in reality.", "Seneca"],
    ["Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"],
    ["Nature does not hurry, yet everything is accomplished.", "Lao Tzu"],
    ["He who knows he has enough is rich.", "Lao Tzu"],
    "Unclench your jaw. Whatever it is, it can wait one minute.",
    "There's a stillness in you that no noise has ever reached.",
    "Take the stairs of the day one at a time.",
    "The tea doesn't care how busy you are. Let it cool and enjoy it anyway.",
    "Do one thing at a time and let it be enough.",
    "Even a long day ends at the same hour as a short one.",
    "Soften your plans a little. Life will meet you halfway.",
    "You can be at peace with your list without finishing it.",
    "Wind down the way the sun does: unhurried, and without apology.",
    "Calm is a skill. Today is a fine day to practise.",
    "Nothing is as loud at night as it was at noon.",
  ],
  courage: [
    "Do it scared. Scared and doing beats calm and waiting.",
    "Courage is a small voice at the end of the day saying, 'I'll try again tomorrow.'",
    "The first step is rarely brave-looking. It just looks like starting.",
    "You've survived every hard day so far. That's a decent record.",
    "Fear is information, not instruction.",
    "Say the thing. Send the message. Open the door.",
    "A nervous 'yes' is still a yes.",
    "Brave people are just people who went anyway.",
    "Whatever you're avoiding is usually smaller up close.",
    "The version of you who is not afraid is on the other side of one awkward minute.",
    ["I learned that courage was not the absence of fear, but the triumph over it.", "Nelson Mandela"],
    ["The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"],
    ["You must do the thing you think you cannot do.", "Eleanor Roosevelt"],
    ["Let me not pray to be sheltered from dangers but to be fearless in facing them.", "Rabindranath Tagore"],
    ["Courage starts with showing up and letting ourselves be seen.", "Brené Brown"],
    ["Fall seven times, stand up eight.", "Japanese proverb"],
    "Be a little braver than you were yesterday. That's the whole plan.",
    "You don't need a clear path, only the next visible step.",
    "Ask the question you're afraid to ask. The answer is rarely as sharp as the silence.",
    "Take the risk of being a beginner again.",
    "Sometimes bravery sounds like 'I don't know, but I'll find out.'",
    "Your comfort zone is lovely, but nothing grows there.",
    "Walk toward it. The shadow is bigger from far away.",
    "Do the hard thing first and let the rest of the day be easy.",
    "You are not too late, too old, or too behind to begin.",
    "A little courage, repeated daily, becomes a character.",
    "Make the call. Future you is already grateful.",
    "No one feels ready. They begin and become ready.",
    "It's okay if your voice shakes. Keep talking.",
    "Be willing to look clumsy on the way to being good.",
    "Dare to take up space in your own life.",
  ],
  discipline: [
    ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant"],
    ["Well done is better than well said.", "Benjamin Franklin"],
    ["Lost time is never found again.", "Benjamin Franklin"],
    ["Energy and persistence conquer all things.", "Benjamin Franklin"],
    ["Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"],
    ["Don't count the days, make the days count.", "Muhammad Ali"],
    ["Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison"],
    "Show up on the days you don't feel like it. Those are the days that build you.",
    "Motivation gets you started. A routine gets you finished.",
    "Small and daily beats big and occasional.",
    "Do the boring part. That's where most of the progress hides.",
    "Make it so easy to start that you can't say no.",
    "Ten minutes today is better than a perfect plan tomorrow.",
    "A habit isn't built by intensity. It's built by returning.",
    "Decide once, then stop deciding every morning.",
    "Keep the promise you made to yourself. It's the one that matters most.",
    "Consistency is quiet. It doesn't need an audience.",
    "The work does not need you to be inspired, only present.",
    "Start before you feel ready; feeling ready arrives mid-task.",
    "Tidy the next small thing. Momentum is made of small things.",
    "You don't rise to your goals. You fall to your routines, so build good ones.",
    "Discipline is just kindness to your future self.",
    "Same time, same place, same small step. Let the calendar do the convincing.",
    "A rough session still counts. Showing up is the rep.",
    "Don't break the chain, but if you do, restart the same day.",
    "Do what you said you'd do, especially when no one is checking.",
    "The first five minutes are the hardest. Everyone knows this, so just survive them.",
    "What you do on an ordinary Tuesday is what your life is made of.",
    "Put your shoes by the door tonight. Let the morning be decided already.",
    "Doing it badly is better than not doing it at all.",
    "Progress is boring up close and amazing from far away.",
  ],
  hope: [
    ["Even the darkest night will end and the sun will rise.", "Victor Hugo"],
    ["Faith is the bird that feels the light and sings when the dawn is still dark.", "Rabindranath Tagore"],
    ["Although the world is full of suffering, it is full also of the overcoming of it.", "Helen Keller"],
    ["It's the possibility of having a dream come true that makes life interesting.", "Paulo Coelho"],
    "This is a chapter. It is not the whole book.",
    "Things can turn around faster than you expect, and often quietly.",
    "Today's worry will be a story you tell someday, probably with a smile.",
    "Not yet is not never.",
    "There are good days ahead that haven't been scheduled yet.",
    "A small light is still a light. Keep yours on.",
    "You have been lost before and found your way. You will again.",
    "Spring doesn't ask winter for permission.",
    "Somewhere, a good surprise is already on its way to you.",
    "Hope isn't pretending it's fine. It's believing it can be better.",
    "The best chapters are often the ones that started in a bad week.",
    "Plant the seed even if you won't see the tree for a while.",
    "One good thing can change the shape of a whole week.",
    "The door that closed made room for a window you haven't noticed yet.",
    "You are closer than you think, even if it doesn't feel like it.",
    "Keep going. The view changes when you do.",
    "What looks like a dead end is sometimes just a corner.",
    "Tomorrow is a blank page with your name on it.",
    "Let the future surprise you. It's good at that.",
    "Every expert once had a day when nothing worked.",
    "The tide always comes back in.",
    "Imagine one thing going right today. Now let it.",
    "Good things take their time and show up on time.",
    "Better days are not a rumour.",
    "Today you are allowed to expect something kind.",
    "Wait with a light heart. Waiting is not losing.",
    "You're one idea, one call, or one afternoon away from a better direction.",
  ],
  "self-worth": [
    "You are not behind. You are on your own road.",
    "Your worth is not a to-do list, and it isn't checked off when the day ends.",
    "You are allowed to be a work in progress and a masterpiece at the same time.",
    "Talk to yourself like someone you're proud of.",
    "You don't have to earn rest. You're a person, not a machine.",
    "The way you keep trying says a lot about who you are.",
    "You've carried more than anyone knows. Be proud of that.",
    "Being imperfect and showing up anyway is a kind of strength.",
    "Your pace is not a flaw.",
    "You are enough on the days you do a lot, and enough on the days you do a little.",
    "Compare yourself to who you were last year, not to a stranger's highlight reel.",
    "You deserve the patience you give to others.",
    "Take up your place in the room. It was set for you.",
    "You are more than your hardest day.",
    "Don't shrink to be easier to hold.",
    "Kindness to yourself is not a luxury. It's maintenance.",
    "You were never meant to do it all. You were meant to do your part.",
    "Not everything you are shows on the outside, and that's allowed.",
    "You have a way of seeing the world that no one else has.",
    "Believe the people who believe in you, at least until you can do it yourself.",
    "You are allowed to change your mind, your plans, your path.",
    ["Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson"],
    ["Be faithful in small things because it is in them that your strength lies.", "Mother Teresa"],
    ["Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"],
    "Your effort counts even when no one sees it.",
    "You are someone's good news today, whether you know it or not.",
    "A mistake is not a verdict. It's a Tuesday.",
    "Be proud of the small win. It has your name on it.",
    "Your story is allowed to be slower than someone else's.",
    "You don't have to be the loudest to matter.",
    "Treat yourself like a friend you plan to keep.",
  ],
  gratitude: [
    "Notice three small good things today. They're always there.",
    "A warm drink, a working phone, a quiet minute. That's already a lot.",
    "Say thank you out loud today. To someone, to anyone.",
    "Gratitude turns what you have into enough.",
    "Someone helped you get here. Remember them kindly.",
    "The ordinary day you're having is someone's wish.",
    "Look at your hands. They did a lot for you today.",
    "Count the meals, the friends, the small mercies.",
    "Be thankful for the version of you that kept going.",
    "Appreciate the people who make your day lighter, and tell them so.",
    "A good night's sleep is a quiet miracle.",
    "Be grateful for what's still here, even when something is missing.",
    "Thank the body that carried you through today.",
    "Today has at least one moment worth remembering. Find it.",
    "Gratitude is attention with a warm heart.",
    "Some of your best days are hiding inside ordinary ones.",
    "Thank the teacher, the stranger, the song that helped.",
    "Love the small routines. They're holding your life together.",
    "Fresh air, clean water, a roof. Pause and let that land.",
    "Be glad of the slow mornings and the early nights.",
    ["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"],
    "Your family, even the difficult parts, is part of your story.",
    "Say 'enough' once today and mean it kindly.",
    "Treat what you have as if you chose it, and you may find you did.",
    "Name something that went right this week. Just one.",
    "Appreciation is free and it makes everything richer.",
    "The simplest dinner tastes better when you notice it.",
    "Write down the good thing before it blends into the day.",
    "Remember when you wished for what you have now.",
    "The small kindnesses people do for you are the real scenery of your life.",
    "Let thankfulness be the last thought tonight.",
  ],
  focus: [
    "One thing, fully, beats five things, partly.",
    "Close the extra tabs. The ones in your head too.",
    "Put your phone face down. Whatever it holds will keep.",
    "Start with the thing that matters, not the thing that's loudest.",
    "Where attention goes, your day goes.",
    "Give this hour your whole attention, then let it go.",
    "A clear next step is worth more than a perfect plan.",
    "Silence the noise, then hear the work.",
    "Set a timer for 25 minutes and become very interested in one task.",
    "Decide what you're not going to do today. That's half of focus.",
    "Don't polish the corner while the room is still bare.",
    "Say no to the good so you can say yes to the important.",
    "One clear intention before opening any screen.",
    "Deep work needs a closed door, even if it's only in your mind.",
    "Single-tasking is a kind of luxury you can give yourself for free.",
    "What is the one thing that makes everything else easier?",
    "Break it down until the next step takes five minutes.",
    "Begin with the end in mind, then begin.",
    "Your attention is the most valuable thing you'll spend today.",
    "A messy start is still a start. Refine it later.",
    "Notice when you drift, and gently come back. That's the whole skill.",
    "Do the hardest thing while your head is fresh.",
    "Park the worry in a note. It'll be there at five, and you can look then.",
    "Today's job: finish one thing properly.",
    "Clear the desk, clear the head, take one step.",
    ["Imagination is more important than knowledge.", "Albert Einstein"],
    ["Take up one idea. Make that one idea your life.", "Swami Vivekananda"],
    ["Start where you are. Use what you have. Do what you can.", "Arthur Ashe"],
    "Pick the three that matter. The rest are just noise wearing a to-do-list costume.",
    "Finish the sentence. Then the paragraph. Then the page.",
    "Focus is saying 'not now' to the shiny and 'yes' to the steady.",
  ],
  "bounce-back": [
    ["Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett"],
    ["I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"],
    ["The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"],
    ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
    ["When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"],
    ["You may not control all the events that happen to you, but you can decide not to be reduced by them.", "Maya Angelou"],
    ["We may encounter many defeats but we must not be defeated.", "Maya Angelou"],
    ["Difficulties strengthen the mind, as labor does the body.", "Seneca"],
    "A bad day is not a bad life.",
    "Missed a day? Begin again. No speech required.",
    "You fell down. That's nothing new for anyone who has ever learned to walk.",
    "Failure is a draft. Edit and go again.",
    "The comeback doesn't have to be dramatic. A small step forward is plenty.",
    "Dust off, not down. You're not the same person who fell.",
    "Let yesterday teach you and then let it go.",
    "What went wrong can be a map of what to do next.",
    "Try again, but this time with what you learned.",
    "You didn't lose. You found out one way that doesn't work.",
    "A setback is a pause, not a stop.",
    "The streak broke. The person didn't.",
    "Reset the plan, not your worth.",
    "Every restart is proof that you haven't quit.",
    "You've bounced back before. Muscle memory is real.",
    "Be proud you're still trying after the hard bit.",
    "Don't judge the whole week by one rough afternoon.",
    "Start small again. Smaller than last time if that helps.",
    "Forgive yesterday's version of you. They were doing their best with what they knew.",
    "Going again is the whole secret.",
    "The scar is proof you healed.",
    "Falling behind is only a story until you take the next step.",
    "Today is a clean slate and it doesn't ask about yesterday.",
  ],
};

export const EN1 = build("en1", ROWS);
