import { build, type QuoteRows } from "./types";

/** English, part 2: work, mornings, learning. */
const ROWS: QuoteRows = {
  calm: [
    ["It's not what happens to you, but how you react to it that matters.", "Epictetus"],
    ["Make the best use of what is in your power, and take the rest as it happens.", "Epictetus"],
    ["No man is free who is not master of himself.", "Epictetus"],
    ["It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"],
    "The inbox will still be there. Your evening won't.",
    "Take a slow walk with no destination and let your thoughts finish themselves.",
    "A deep breath is the cheapest reset there is.",
    "Let the kettle boil while you do absolutely nothing.",
    "Morning light is free medicine. Stand in it for a minute.",
    "Leave a little space between tasks. It's where you catch up with yourself.",
    "Close your eyes for ten seconds. The world will wait.",
    "When it's too loud outside, find the quiet in your hands, your feet, your breath.",
    "You can pause without being behind.",
    "Calm doesn't mean nothing is happening. It means you're not being dragged by it.",
    "Choose one slow thing today and do it properly.",
    "Water your own garden and let the neighbours worry about theirs.",
    "A tidy corner can make a tired mind feel lighter.",
    "Switch the notifications off for an hour. See who you are without them.",
    "Even the busiest day has a window if you look for it.",
    "Drink some water. Stretch. Then decide again.",
    "Pause before replying. The first draft of anger is rarely your best.",
    "Sit with your tea like it's the most important meeting of the day.",
    "The mind slows down when the body is allowed to.",
    "It's evening. The day has done what it could.",
    "Breathe out longer than you breathe in.",
    "You don't need to solve tomorrow tonight.",
    "A little boredom is good for the soul. Let it visit.",
    "Soft music, low light, no demands. That's a plan too.",
    "Stop fixing the past. Let this moment be unfixed and fine.",
    "Do a task slowly and notice that you can.",
    "A walk around the block resets more than you'd expect.",
  ],
  courage: [
    ["Go confidently in the direction of your dreams! Live the life you've imagined.", "Henry David Thoreau"],
    ["You can't cross the sea merely by standing and staring at the water.", "Rabindranath Tagore"],
    ["Arise, awake, and stop not till the goal is reached.", "Swami Vivekananda"],
    ["Stay hungry, stay foolish.", "Steve Jobs"],
    ["I have learned over the years that when one's mind is made up, this diminishes fear.", "Rosa Parks"],
    "Begin the conversation you've been rehearsing in your head.",
    "Ask for the help. Strong people do.",
    "Put your hand up. Even if your voice wobbles.",
    "You can be nervous and capable at the same time.",
    "The leap feels huge only before you've left the ground.",
    "Trust yourself a bit more than you doubt yourself.",
    "One brave email can change a month.",
    "Say yes to the invitation that scares you a little.",
    "Be the first to say hello. Someone's grateful you did.",
    "Dare to be a beginner, again and again.",
    "Not knowing how is not a reason not to begin.",
    "Courage is a muscle. Today is leg day.",
    "Talk about the hard thing. It shrinks when you do.",
    "Some doors only open from your side.",
    "Choose the discomfort of growth over the discomfort of regret.",
    "Take the first step even if the staircase is hidden in fog.",
    "Make the decision, and then become the person who made it right.",
    "Apply for the thing. The worst answer is the one you give yourself by not trying.",
    "Be bold in small ways. They add up.",
    "Show your work before it feels finished.",
    "Disagree politely. Your view is also part of the picture.",
    "Stand a little taller. It changes how you feel.",
    "Risk the awkward moment; it's usually over in seconds.",
    "Dream out loud. Quiet dreams don't get helpers.",
    "You are braver than the last time you doubted yourself.",
    "Some of the best days start with a nervous stomach.",
  ],
  discipline: [
    ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"],
    ["Dream, dream, dream. Dreams transform into thoughts and thoughts result in action.", "A. P. J. Abdul Kalam"],
    ["If you want to shine like a sun, first burn like a sun.", "A. P. J. Abdul Kalam"],
    "Do your morning routine like it's a promise, not a punishment.",
    "Plan tomorrow's first step tonight.",
    "The best productivity trick is a good night's sleep.",
    "Put the hard task at the start of the day, when you still have choices.",
    "Make a rule: no phone until the first thing is done.",
    "Prepare your environment and your willpower won't have to work so hard.",
    "Be the person who finishes what they start, one small thing at a time.",
    "Mastery is a lot of ordinary days stacked up.",
    "Repetition is how a clumsy thing becomes a quiet strength.",
    "Don't wait to feel like it. Act, and the feeling follows.",
    "Write it down, schedule it, show up. That's the whole system.",
    "Treat your calendar as a statement of what you value.",
    "Keep going when it's dull. Dull is where most of the growth lives.",
    "Do the practice, not just the planning of the practice.",
    "A tiny version done daily beats a heroic version done never.",
    "You don't need more time, you need a fixed time.",
    "Keep your word to yourself; it builds trust from the inside.",
    "Be gentle but firm with yourself, like a good coach.",
    "Done is a feeling worth chasing.",
    "Your future is quietly built from this afternoon.",
    "Count reps, not results. Results come later.",
    "Habits don't care about your mood. They respond to your repetitions.",
    "Take a short break, then return. Discipline includes rest.",
    "The best plan is the one you will actually follow.",
    "Do the dishes, send the invoice, make the call. Tiny wins are real wins.",
    "Order in small things makes room for big ones.",
    "Think of it as an appointment with the person you're becoming.",
    "Win the morning and the day is easier to lead.",
  ],
  hope: [
    "Every season passes, including this one.",
    "A clear day is coming. You can't see it yet, but it's on the schedule.",
    "Maybe this is the part of the story where things start to turn.",
    "Hold on to what you hoped for last year; some of it is quietly on its way.",
    "Nothing stays stuck forever, not even stuck.",
    "There's a version of this that works out. Aim your effort at that one.",
    "A lucky break is often just hard work that finally got noticed.",
    "You haven't run out of chances. You've only run out of this one.",
    "Even a cloudy sky is lit from above.",
    "Someone out there will be glad you kept going.",
    "Keep your eyes on the horizon. It keeps moving closer.",
    "There's plenty of time for good things to happen.",
    "Slowly, and then suddenly, things get better.",
    "Good news tends to arrive when you've stopped refreshing.",
    "The future version of you is rooting for you to take today seriously and gently.",
    "Hope is a decision you can make again every morning.",
    "A rainy day waters a dozen things you can't see.",
    "Keep a small plan for good things in your pocket.",
    "Your best work may still be ahead of you.",
    "What you're building might take longer than you wish, but it's real.",
    "Imagine yourself a year from now thanking you for today.",
    "Things you can't see yet are growing.",
    "Be optimistic about the long run and patient about the short one.",
    "There's more room for joy in your life than your worries suggest.",
    "Carry on. Plenty of mornings still have your name on them.",
    "Hard seasons grow deep roots.",
    "You are allowed to look forward to something.",
    "A small win today is a promise about next month.",
    "The story's not over, and you hold the pen.",
    "You'll look back and be surprised how far this carried you.",
    "Some of the best days of your life haven't happened yet.",
  ],
  "self-worth": [
    ["The unexamined life is not worth living.", "Socrates"],
    ["Out of suffering have emerged the strongest souls.", "Khalil Gibran"],
    "You are not a project to be fixed. You're a person to be understood.",
    "Your best is different every day, and it's always enough.",
    "You belong at the table you worked hard to reach.",
    "Nobody is you, and that's your whole advantage.",
    "You can be proud and still keep growing.",
    "Don't wait for permission to take your work seriously.",
    "Your voice matters. Use it even when it's quiet.",
    "You are not an inconvenience. You're a human with needs.",
    "Pat yourself on the back for the things nobody noticed.",
    "Give yourself the credit you give your friends.",
    "Reject the idea that you must be tireless to be worthy.",
    "You are allowed to take pride in what you've built.",
    "You don't need to prove anything to anyone today.",
    "Respect the person who keeps trying, even when it's you.",
    "Your quiet persistence is a form of greatness.",
    "Rest is a right, not a reward.",
    "You are not your productivity.",
    "Value your time. It's the only version you get.",
    "You've been learning all along, even when it didn't look like progress.",
    "Be the kind of friend to yourself that you'd want on a hard day.",
    "You have gifts that look ordinary to you because they come naturally.",
    "Hold your head up. You've done more than you give yourself credit for.",
    "You are not too sensitive. You're someone who notices.",
    "You're not late. You're arriving the way you're meant to.",
    "Say 'I did well' and see if it sticks.",
    "Let the good things people say about you actually land.",
    "Your worth was never on the scoreboard.",
    "Be loyal to your own growth.",
    "Wear your effort proudly, not apologetically.",
  ],
  gratitude: [
    ["Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson"],
    "Thank your younger self for getting you this far.",
    "Be thankful for the friend who texts back at midnight.",
    "Notice the people who have always shown up quietly.",
    "Today's gift might be a green light or a kind word. Look out for it.",
    "A hot meal is a small celebration.",
    "Be grateful for your questions. They're how you learn.",
    "Thank the people behind the scenes who make your day work.",
    "Your phone has the whole world on it, and a loved one's voice. That's a miracle too.",
    "Practise saying 'thank you' instead of 'sorry' sometimes.",
    "Enjoy a sunset like it's the only one. It is, for today.",
    "Gratitude is a quiet kind of wealth.",
    "Be glad for good teachers, past and present.",
    "Think of someone who made your life better and let them know.",
    "Home doesn't have to be fancy to be a blessing.",
    "Your lungs have been working all day without being asked. Thank them.",
    "Some of your favourite things are free.",
    "The people who forgive your bad days are rare. Hold them close.",
    "Be thankful for second chances and third ones.",
    "Small joys deserve a proper welcome.",
    "A kind stranger is a small miracle on an ordinary street.",
    "Hold on to the thing that made you smile today.",
    "A well-timed laugh is a gift.",
    "Thank the hard days for what they taught you, even if you didn't enjoy the lesson.",
    "Be thankful for the chance to try again tomorrow.",
    "Say thank you to someone older than you for what they've seen.",
    "Today you have food, a bed, and someone who might think of you. That's worth a pause.",
    "The best gifts are time and attention. Give and receive them well.",
    "Honour the people who believed in you before you did.",
    "Thank the music that carried you through.",
    "Close the day with one honest 'thank you'.",
  ],
  focus: [
    "Do what you can, with what you have, where you are.",
    "Make the first hour of the day sacred. Protect it.",
    "A cluttered desk can make a cluttered mind. Clear a small square.",
    "Do the next right thing, then the one after.",
    "Mute the group chat. It will survive without you for 30 minutes.",
    "Work in sprints. Rest in full stops.",
    "Turn the big task into a checklist. Then it's just a series of small ones.",
    "Don't confuse busy with effective.",
    "Answer one question: what would make today a success?",
    "One screen, one task, one cup of tea.",
    "Perfection can wait. Progress is on the clock.",
    "Be where your feet are.",
    "Batch the small stuff. Protect the big stuff.",
    "The thing you keep postponing is probably the thing to start with.",
    "If it takes under two minutes, do it now. Otherwise, schedule it.",
    "Pause between tasks. Resetting your attention is part of the job.",
    "Drop what doesn't serve today's main goal.",
    "Let a deadline be a friend, not a villain.",
    "Check email twice a day and see what happens to your head.",
    "Write down the three outcomes for today. Everything else is bonus.",
    "A short walk can untangle a long problem.",
    "Do the part you can do now. Don't let the unknown part stop you.",
    "Gather your tools before you start. Then don't stop.",
    "When your mind wanders, name it kindly and return.",
    "Work with the grain of your energy, not against it.",
    "Define done before you begin.",
    "Start with a bad first draft. The page can't improve a blank.",
    "Ask: is this the best use of the next hour?",
    "Trust the process, but check the clock.",
    "Take a single deep breath before each new task.",
    "You can do hard things. Hard things in order.",
  ],
  "bounce-back": [
    ["I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"],
    ["It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all.", "J. K. Rowling"],
    ["What does not kill me makes me stronger.", "Friedrich Nietzsche"],
    ["I am a slow walker, but I never walk back.", "Abraham Lincoln"],
    ["Everything can be taken from a man but one thing: the last of the human freedoms, to choose one's attitude in any given set of circumstances.", "Viktor Frankl"],
    "Allow yourself a messy middle. It leads somewhere.",
    "It's okay to have a bad day. Don't let it write the whole week.",
    "Pick up one tiny thing you dropped. Then another.",
    "The only way out is through, and you're already on the path.",
    "Not hitting the target means you've collected data.",
    "Sometimes the best thing you can do is rest, then resume.",
    "Getting back on is the whole skill.",
    "You are allowed to restart as many times as you need.",
    "Forget the streak. Start a new one today.",
    "Rejection redirects. It rarely ends the road.",
    "What you lost is not the measure of what you can still do.",
    "Disappointment is the price of caring. Care again.",
    "Your last attempt taught you how to do the next one better.",
    "When plans fall apart, make a smaller plan.",
    "Don't read a sad chapter as the end of the book.",
    "Take the lesson, leave the shame.",
    "You've been through harder than this and found a way.",
    "Recovery isn't a straight line, but it is a direction.",
    "A wobble isn't a collapse.",
    "You can begin again from exactly where you are.",
    "A comeback starts with showing up for the boring parts.",
    "Don't quit on the day that's the hardest. Quit on a good day, if you must.",
    "Even a slow restart is a restart.",
    "Hard seasons end. You'll still be here.",
    "Breathe, regroup, go again.",
    "Be someone who gets up one more time than they fall.",
  ],
};

export const EN2 = build("en2", ROWS);
