import { build, type QuoteRows } from "./types";

/** English, part 3: people, body, time, small moments. */
const ROWS: QuoteRows = {
  calm: [
    "Put the day down gently, like a book you'll open again tomorrow.",
    "The sky does not rush to be dark. Neither should you.",
    "Rain on the window is a free lullaby.",
    "Stretch your neck, roll your shoulders, unclench your hands.",
    "Be a good guest in your own body today.",
    "Talk slower. Think slower. Often the day lets you.",
    "There is nothing to catch up on in this exact second.",
    "A cup of tea has never solved everything, but it has softened a lot.",
    "Light a candle, or just dim the room. Signal to your mind that it's evening.",
    "Be a lake, not a river, for a while.",
    "A pause between two sentences makes the second one wiser.",
    "You can be okay without being excited.",
    "Quiet doesn't need to be filled.",
    "Every hour doesn't have to be useful to be worthwhile.",
    "The moon does a lot of work and never looks hurried.",
    "Take a bath, or just run warm water over your hands.",
    "Your calm is contagious. Share it.",
    "Sit near a window. Watch something move slowly.",
    "Say 'I'm okay right now' and check whether it's true.",
    "Nothing has to be perfect for tonight to be peaceful.",
    "Let go of the ninth thing on the list.",
    "Walk to the end of the road and back, empty-handed.",
    "Take the long way home for the sky, not for the distance.",
    "Quiet routines are the foundations of good days.",
    "Today, practise leaving things unfinished with a clear conscience.",
    "A deep breath before opening your eyes can set the whole morning.",
    "Stillness is not the opposite of action; it's where good action comes from.",
    "Your body keeps a quieter clock than your phone. Listen to it.",
    "Slow down enough to taste your food.",
    "Sit with the feeling instead of fighting it. It passes faster that way.",
    "You are allowed to be unreachable for an hour.",
  ],
  courage: [
    "Tell the truth kindly. It's one of the bravest things you can do.",
    "You can say no and still be a good person.",
    "Walk into the room as if you're meant to be there. You are.",
    "Apologise first. It takes more strength than being right.",
    "Be honest about what you need.",
    "Leave the place that makes you smaller.",
    "Start the project that scares you a little and excites you a lot.",
    "Admit you don't know. Then be the first to learn.",
    "Let someone see you try, and fail, and try again.",
    "Stop waiting for a sign. This is it: go.",
    "Do the right thing quietly. It counts the same.",
    "Hold your ground gently.",
    "Speak up for someone who isn't in the room.",
    "Share the idea even if it's half-formed.",
    "Take the new route. Familiar roads have taught you all they can.",
    "Tell them you care before it's too late.",
    "Being vulnerable is a strength with the volume turned down.",
    "Choose to be hopeful in a room full of cynics.",
    "Stand up for your own plans.",
    "Sometimes you have to start before the whole plan is clear.",
    "Say 'I need a break' and mean it.",
    "Give your heart another chance to be wrong, and right.",
    "Face the thing today. Tomorrow's version of it is the same size, or bigger.",
    "Your story deserves to be told by you.",
    "Trust that you can handle whatever comes next.",
    "Try a new thing badly. That is how everyone started.",
    "Start where you're at. That's the only place anyone can.",
    "Say 'let me try' more often than 'I can't'.",
    "Be someone who offers help first.",
    "Let go of what's gone, bravely, and make room.",
    "You have made hard decisions before. Your judgment has history.",
  ],
  discipline: [
    "Keep a promise to yourself this week. Just one.",
    "Little by little, a little becomes a lot.",
    "Choose the harder right over the easier wrong, even in small things.",
    "Stack a new habit on an old one. Let it ride along.",
    "Put your goals where you can see them.",
    "Dress for the work you want to do.",
    "Lay out tomorrow's clothes. Tomorrow-you will notice.",
    "Say the plan out loud. It becomes more real.",
    "A short run, a short read, a short practice. Short is still something.",
    "If you can't do an hour, do ten minutes. Continuity beats quantity.",
    "A tidy system makes discipline easier.",
    "Reward the effort, not only the result.",
    "Make the goal so small it's almost embarrassing. Then do it daily.",
    "Pre-decide: when this happens, I will do that.",
    "Don't negotiate with the alarm clock. Just stand up.",
    "Hard work is quiet. It doesn't announce itself.",
    "What you repeatedly practise, you quietly become.",
    "Don't compare your Day 3 with someone else's Day 300.",
    "Do the unglamorous thing. Someone you admire did, repeatedly.",
    "Self-control is a gift you can give your future self.",
    "Pay yourself first: your time, your goals, your energy.",
    "Begin the day by doing something your future self will be proud of.",
    "Be patient with the process and impatient with the excuses.",
    "Practise the basics until they feel boring, then keep going.",
    "You can have a bad day and still keep the habit.",
    "Fall in love with the process, not the finish line.",
    "Be loyal to your routines on the days they're hard to love.",
    "Success loves the quiet repetition nobody sees.",
    "Choose your hard: the discipline of a routine or the weight of regret.",
    "A good routine is a kind of freedom.",
    "Work a little, rest a little, repeat.",
  ],
  hope: [
    "Light is patient. It will find the gap.",
    "Someone is on the way to you with exactly the right news.",
    "You are already planting the garden you'll sit in next year.",
    "It won't always feel like this.",
    "The calendar has a lot of days you haven't met yet, and some will be lovely.",
    "A single honest 'yes' can open a whole year.",
    "Nothing is wasted: not the waiting, not the wrong turns.",
    "Hold your dreams loosely, but don't drop them.",
    "Today's small effort is next season's harvest.",
    "The future isn't only coming at you. You are walking toward it.",
    "Keep an eye out for a pleasant surprise. They love hiding in ordinary days.",
    "The light at the end of the tunnel is not a train; it's the end of the tunnel.",
    "Your life has more room for good luck than you think.",
    "What if this turns out better than you fear?",
    "Perhaps the best plans are the ones you haven't met yet.",
    "Keep hoping. It's free, and it works better than you'd think.",
    "A bruised sky still turns to dawn.",
    "Hope looks like making the bed, answering one email, and going outside.",
    "New beginnings often wear disguises of endings.",
    "Beautiful things take their time. So do you.",
    "A year from now this will be a memory, maybe even a funny one.",
    "Hold space for the good news.",
    "Dawn is the proof that waiting works.",
    "You get to choose which story you tell about this season.",
    "In the long run, kindness and effort tend to find their way home.",
    "There's still time to turn this week around.",
    "Keep the door open for luck.",
    "Joy is a patient guest. It will come back.",
    "Believe the next chapter is kinder.",
    "A tiny seed holds a whole tree. So does an ordinary day.",
    "You've got a lot of good left in you.",
  ],
  "self-worth": [
    "Your presence is a gift even when you feel empty-handed.",
    "Stop apologising for taking up space.",
    "You don't have to be extraordinary to be worth loving.",
    "Keep a list of what you're good at, and read it on harder days.",
    "You are worth the time it takes to take care of yourself.",
    "Let your effort speak louder than your doubts.",
    "You are allowed to be proud of ordinary progress.",
    "Your feelings are valid even when they're inconvenient.",
    "You have survived 100% of your worst days.",
    "Wanting more for yourself isn't selfish.",
    "Don't let one critic outweigh ten kind voices.",
    "Believe you're worth the good things coming your way.",
    "The way you treat yourself sets the standard for others.",
    "You're not 'too much'. You may just be around the wrong people.",
    "Show up as you are. That's the only version they can actually meet.",
    "You are more capable than your fear is telling you.",
    "Give yourself the same grace you give strangers.",
    "You've grown in ways nobody sees.",
    "Value what makes you different.",
    "Take compliments like gifts, not trick questions.",
    "You don't have to be in a hurry to be worth something.",
    "Be gentle. You're still learning how to be you.",
    "Your best friend would say you're doing fine. Believe them.",
    "You are enough as you rest, not only as you work.",
    "Self-respect is quiet and doesn't need an audience.",
    "Your needs are not a burden.",
    "You are worth showing up for, starting with you.",
    "You have the right to change, to grow, to start over.",
    "Own your small wins. They're yours.",
    "You carry more strength than you've been credited for.",
    "Choose to be on your own team today.",
  ],
  gratitude: [
    "Thank the day for being what it was.",
    "The little things are the big things that sneak up on you.",
    "A friend who laughs at your jokes is a rare treasure.",
    "Be grateful for what you've learned from the people who left.",
    "Wave to your neighbour. Thank the delivery person. Be a small piece of someone's good day.",
    "Look around the room and find five things you're glad of.",
    "Gratitude changes the colour of an ordinary evening.",
    "Remember what you used to hope for, and notice what's now true.",
    "Be grateful for the places that felt like home.",
    "Even a small kindness remembered is a gift.",
    "Thanks to everyone who has held a door, literal or otherwise.",
    "Give someone a compliment today and watch it come back around.",
    "Be thankful for the version of the story where you kept going.",
    "Your mother's recipe, your friend's laugh: store them carefully.",
    "Today, thank someone for something they think no one noticed.",
    "Be glad of the clean sheets and the quiet streets.",
    "Savour the small, warm moment before it passes.",
    "Notice what your body does for you without asking.",
    "Say grace in your own way before a meal.",
    "Grateful people tend to be lighter people.",
    "Hold a moment of thanks for the road behind you.",
    "Be grateful you have things to look forward to.",
    "The people who knew you at your worst and stayed are family, by any name.",
    "Be thankful for ordinary health, until you can't be.",
    "Let your last thought tonight be one of thanks.",
    "Thank your hands, your eyes, your feet.",
    "Today, be the reason someone feels seen.",
    "Take a photo in your mind of this very ordinary good moment.",
    "Acknowledge the help. Nobody does it alone.",
    "The best things in life are usually already in the room.",
    "Notice, appreciate, repeat.",
  ],
  focus: [
    "Do one honest hour of work and see how far you've come.",
    "Notifications are other people's priorities. Choose yours first.",
    "The most important task today is probably the one you're avoiding.",
    "Let your calendar protect your focus time.",
    "Focus is the new luxury. Guard it.",
    "A good question is worth ten fast answers.",
    "Don't research forever. Start something small.",
    "Do less, but do it with your whole mind.",
    "Make the big decision first thing, while you're clear.",
    "Choose your top priority and let it lead the day.",
    "Distractions are patient. Be more patient.",
    "Plan the work, then work the plan, then close the laptop.",
    "Ten focused minutes beats an hour of half-attention.",
    "Define the next action so clearly that you can't misunderstand it.",
    "Put the task in front of you and stay with it for one round of tea.",
    "Name what you're avoiding. It loses a lot of its power.",
    "Single-tasking is a superpower hiding in plain sight.",
    "If everything is a priority, nothing is. Pick one.",
    "Your phone is a tool. Let it be one for the next hour.",
    "Be so absorbed in the work that time forgets to count.",
    "Practise the art of ignoring the unnecessary.",
    "Write the first sentence badly. Then you can fix it.",
    "Keep your goal visible, your schedule simple.",
    "Fewer open loops, more quiet mind.",
    "Check your list, pick the one, start.",
    "Look at the problem long enough to see its shape.",
    "Block time for the work you care about most.",
    "A timer is a gentle boss.",
    "Pay attention on purpose.",
    "Make yourself a small ritual to start the work: tea, desk, one deep breath, go.",
    "Don't skip lunch to win the day. A rested mind is a sharper one.",
  ],
  "bounce-back": [
    "Rough patch? You're allowed to be slow through it.",
    "Rebuilding is also a kind of progress.",
    "After the storm, the first thing you do is sweep the step. Start there.",
    "No one's life is a straight line. Look at the squiggles with kindness.",
    "Give yourself credit for getting up today.",
    "Every comeback starts with 'okay, what now?'",
    "You are allowed to take a lighter version of the plan.",
    "Today you'll do a smaller thing. That's okay. Smaller is still forward.",
    "Even when things fall apart, you remain the person who can put them together.",
    "A failed attempt is proof of an attempt.",
    "Let the mistake teach you quietly and leave.",
    "Don't let one off-day become an off-year.",
    "Get back to basics: sleep, water, a walk, one task.",
    "You're not starting from zero. You're starting from experience.",
    "A setback is a set-up for a comeback, as long as you stay curious.",
    "Take a day. Then take a step.",
    "You did not come this far only to come this far.",
    "Recover first, then rebuild.",
    "Make peace with what went wrong, then make a small plan.",
    "The streak may be gone, but the habit isn't.",
    "Start today with the version of the habit that is easiest.",
    "Bounce back does not mean bounce fast. Take your time.",
    "Choose a gentle restart.",
    "You can't go back and change the start, but you can start now and change the ending.",
    "A hard chapter doesn't cancel the good ones.",
    "Your effort wasn't wasted; it just changed direction.",
    "You are still here, and that is a form of winning.",
    "Failure feels final only for a moment.",
    "There's no shame in a second try, or a tenth.",
    "Come back to the work with fresh eyes and kind hands.",
    "Try a different way. Persistence has more than one door.",
  ],
};

export const EN3 = build("en3", ROWS);
