import { build, type QuoteRows } from "./types";

/** English, part 4: longer thoughts and the last of the set. */
const ROWS: QuoteRows = {
  calm: [
    ["The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"],
    ["The mind is not a vessel to be filled but a fire to be kindled.", "Plutarch"],
    "You can't pour from an empty cup, so fill yours first, and without guilt.",
    "Let this moment be exactly as ordinary as it is.",
    "When the world speeds up, deepen your breath.",
    "Rest your eyes on something green.",
    "The best part of the evening is often the part with no plans.",
    "Smile at nothing in particular. It helps more than it should.",
    "Pour a glass of water, sit down, and notice you are safe for now.",
    "Take today as it comes, one sip at a time.",
    "A tired mind gets a second wind from a small kindness.",
    "Not every storm is coming to disrupt your life. Some are here to clear your path.",
    "Choose peace over proving a point.",
    "Silence can be a kind of conversation with yourself.",
    "In a noisy world, a quiet routine is a form of strength.",
    "Look up. The sky is bigger than the problem.",
    "Walk slowly enough to notice something new on a familiar street.",
    "Something small and sweet can end a hard day well.",
    "Anxiety lives in the future. Come back to now. Now is usually manageable.",
    "Count backward from ten, slowly. See the day from a bit further away.",
    "There is a soft place in every day. Find it.",
    "Lean back. You're allowed.",
    "Whatever you can't finish tonight will be waiting, smaller, in the morning.",
    "Smooth sea, rough sea: the captain still breathes.",
    "Close the day with something warm and something kind.",
    "Notice the ground under your feet. It is holding you.",
    "Let the dishes wait. Sit with the people you love.",
    "Say less. Mean more.",
    "Wear comfortable clothes and a patient face.",
    "Let the afternoon be slow. It has earned it.",
    "You are allowed to enjoy being unproductive.",
    "A soft landing is part of every plan.",
    "Evening comes whether or not you finished; let it come kindly.",
  ],
  courage: [
    ["Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure.", "Theodore Roosevelt"],
    ["Be water, my friend.", "Bruce Lee"],
    "Say what you mean, and be kind about it.",
    "You are allowed to outgrow the place you came from.",
    "Take the leap before you have a safety net, then build one on the way.",
    "Your 'what if it works?' deserves as much airtime as your 'what if it doesn't?'.",
    "Brave isn't loud. It's steady.",
    "Let your actions be quietly braver than your words.",
    "When you doubt, move a little. Doubt hates momentum.",
    "Pick up the phone. Most hard calls end with relief.",
    "Show someone your unfinished work. That's how it gets finished.",
    "Face the mirror and tell it the truth gently.",
    "You were built for more than hiding.",
    "Leave room for the version of you that tries.",
    "The moment you decide to try, you already changed.",
    "Don't wait for the fear to leave. Bring it along.",
    "You can't be brave without something at stake. Be glad it matters.",
    "The first 'no' hurts. The hundred after don't, and one 'yes' changes everything.",
    "Start before you know how. That's how you find out.",
    "Be a little uncomfortable on purpose, once a day.",
    "Cry if you need to, then do the thing.",
    "Do right, even when it's awkward.",
    "Take a deep breath and take the stage.",
    "Your doubts are loud but they're rarely right.",
    "Walk into the unknown with curiosity in your pocket.",
    "Risk a little embarrassment for a lot of growth.",
    "Say it out loud: 'I'm going to try.'",
    "Start the difficult thing at its easiest point.",
    "Hold your head up. You've handled worse.",
    "You are one decision from a different day.",
    "Think of the person you'll be proud of in a year, and act like them now.",
    "Courage doesn't roar. Sometimes it whispers, 'again tomorrow'.",
    "Leave the cage door open. Notice you could fly.",
  ],
  discipline: [
    ["Take care of the minutes, and the hours will take care of themselves.", "Lord Chesterfield"],
    "Continuous effort, not strength or intelligence, is the key to unlocking our potential.",
    "A little every day will out-run a lot once a month.",
    "Make today's task so clear you could do it half-asleep.",
    "Put in the hours when nobody's clapping.",
    "The days you don't feel like it are the ones that count double.",
    "Do not let a rough start convince you the day is lost.",
    "Be the kind of person who does the dishes before bed.",
    "Do the thing and forget the drama.",
    "A bad workout, a short study, a messy page: all of them still moved you forward.",
    "Slow progress is still progress. Do not despise small beginnings.",
    "Let your habits do the heavy lifting.",
    "Always leave the next step ready for tomorrow.",
    "Write down tonight what you will do first tomorrow.",
    "Turn 'someday' into a date.",
    "When your motivation naps, let your routine drive.",
    "Practise on purpose, not just by repetition.",
    "Tiny habits, big transformations.",
    "Do what's needed, then do what's wanted.",
    "Your discipline is a love letter to the person you'll become.",
    "Decide the time, protect the time, honour the time.",
    "Hold the line on the small promises.",
    "It isn't sacrifice if you're building something you love.",
    "Treat your goals like appointments you can't miss.",
    "Chunk it, schedule it, do it.",
    "Work steadily and stop at a sensible hour.",
    "Be steady. Fast fades, steady stays.",
    "When in doubt, return to the routine.",
    "Resist the urge to reinvent the plan every day.",
    "Mastery is built from showing up, not showing off.",
    "Every ordinary day you keep your word to yourself, you grow stronger.",
    "Start slow if you must. But start.",
    "Few things are as powerful as a plain, consistent Tuesday.",
  ],
  hope: [
    ["Hope is the thing with feathers that perches in the soul.", "Emily Dickinson"],
    "Where there is love, there is life.",
    "A great day can begin with a small decision.",
    "Maybe what feels like an ending is just a change of scenery.",
    "Don't give up on the day before it has finished surprising you.",
    "You don't have to see the whole staircase. Just take the first step.",
    "Good days are already making their way to you.",
    "The sun comes up every morning without your approval or effort. Neat, isn't it?",
    "A kind future is waiting on your effort and your patience.",
    "You will look back at this and see the beginning of something better.",
    "Today is a perfectly good place for a fresh start.",
    "You've got more tomorrows than worries.",
    "Every flower once had to push through dirt.",
    "The seeds you plant today will not ask whether you believed. They'll just grow.",
    "Look for the helpers, the good news, the glimmers.",
    "Let optimism be your quiet default.",
    "Relief is on its way to you, even if it's late.",
    "The universe has more good ideas than bad ones.",
    "Something lovely is about to happen on a regular weekday.",
    "A small hope, tended daily, grows into a plan.",
    "Today could be the day you remember for good reasons.",
    "Let yourself imagine it going well.",
    "Allow the possibility of being happily surprised.",
    "Your best chapter hasn't been titled yet.",
    "A new opportunity can arrive on the back of an ordinary morning.",
    "It takes only one good conversation to change a season.",
    "The way forward often appears once you start walking.",
    "You are not stuck; you are gathering your strength.",
    "Never underestimate the power of waking up and trying again.",
    "Patience pays in a currency that arrives later but is worth more.",
    "There are more helpful people in the world than you think.",
    "Keep the kettle on. Good news may be on its way.",
    "It's a good time to be alive and to be you.",
  ],
  "self-worth": [
    ["Nothing will work unless you do.", "Maya Angelou"],
    ["Still I rise.", "Maya Angelou"],
    "You are the author of today's page.",
    "You are worthy of a good day.",
    "Respect your limits and honour your effort.",
    "Don't trade your peace for approval.",
    "People who truly like you will like the real you, so be the real you.",
    "Hold your own hand through the hard parts.",
    "Be proud of the quiet strength it took to get here.",
    "You are not an accident; you are an invitation to the world.",
    "Don't let a bad review turn into your inner voice.",
    "You are allowed to enjoy your own company.",
    "Your humanness is not a flaw in the plan.",
    "You are here, and that is enough to start.",
    "The best compliment you can give yourself is to keep your word.",
    "You didn't just survive. You learned.",
    "You were good enough yesterday, and you're good enough today.",
    "You can hold both 'I'm growing' and 'I'm okay as I am'.",
    "Honour your gentler side. It's part of your strength.",
    "You are not a burden; you are a person who occasionally needs a hand.",
    "You're allowed to say 'I'm proud of me'.",
    "You are the only one who has lived your life, so trust your experience.",
    "You are allowed to be wanted, welcomed, and well.",
    "Be your own cheerleader when the stands are empty.",
    "Be gentle with the person who's trying their best.",
    "You've improved more than you realise.",
    "Believe in the person you are becoming.",
    "Your life is not a rehearsal for someone else's standards.",
    "Quiet confidence is also confidence.",
    "Say it with me: 'I am doing okay, and I am allowed to keep going.'",
    "You deserve rest, joy, and decent sandwiches.",
    "You are exactly who the people who love you hoped you'd be.",
    "Whoever you are today, you're welcome here.",
  ],
  gratitude: [
    "Be thankful for what you have; you'll end up having more.",
        "Say thank you to your past self, who made today possible.",
    "Be glad of daylight, a kettle, a working door.",
    "Count the times a stranger was kind to you this week.",
    "Everyday magic hides in small habits: tea, music, a chat, a walk.",
    "Be thankful for hands that heal and voices that comfort.",
    "Sometimes gratitude is just noticing the afternoon sun.",
    "Remember to be grateful for the ones who ask 'how are you?' and mean it.",
    "Think of the first person you'd call with good news. Treasure them.",
    "The roof over your head, the song in your ears: a good life, in pieces.",
    "Be grateful for challenges that made you more patient.",
    "Smile at someone who helped you. It doesn't cost a thing.",
    "Take a moment to be glad you're here to see this day.",
    "Acknowledge one thing you did well today.",
    "Be thankful for second helpings and second chances.",
    "Thank the people who make the unseen things work.",
    "There's always something to thank. Start with the very small.",
    "The best present is the present.",
    "Make a habit of writing three good things at night.",
    "Be grateful for each ordinary Friday.",
    "Thank the rain for the green, and the heat for the shade.",
    "The kindness you give comes back in unexpected ways.",
    "Pause. Look around. Be glad.",
    "Thankfulness is a muscle that grows with use.",
    "Thank someone you haven't thanked yet.",
    "You are surrounded by small mercies. Spot three.",
    "Thank your body for holding up, even on the rough days.",
    "Treasure time with people who feel like home.",
    "Even tonight's tiredness means you used the day.",
    "Be thankful today for something you almost didn't notice yesterday.",
    "An ordinary day is a wonderful thing to be given.",
    "Let thanks be the quiet bookend of your day.",
  ],
  focus: [
    ["Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", "Alexander Graham Bell"],
    "Do not dwell in the past, do not dream of the future; concentrate the mind on the present moment.",
    "The art of focus: one thing at a time, and that thing right now.",
    "Make a short list; make it the right list.",
    "Cut the extras and do the essential.",
    "Bundle your meetings. Spare your mornings.",
    "Close the loop you opened an hour ago.",
    "Prepare tonight for the thing that matters tomorrow.",
    "You don't need a new plan. You need the next ten minutes.",
    "Unplug for one hour and see what you finish.",
    "Look at the single next action, not the mountain.",
    "Be so clear on your why that distractions seem foolish.",
    "If you can't focus, tidy something small and try again.",
    "Fifteen minutes of full attention is better than an hour of drift.",
    "Notice how good it feels to finish one thing.",
    "Let the important thing be obvious.",
    "Use a plain notebook and a plain pen. Fewer tabs, more thinking.",
    "A clear space, a clear mind, a clear step.",
    "Work in a single stream, not ten small rivers.",
    "Say no politely, often, and without a long explanation.",
    "A single priority can carry the whole day.",
    "Place your phone in another room, and enjoy the quiet gap it leaves.",
    "Think in outcomes, not hours.",
    "Be here. The rest can wait its turn.",
    "Calm attention is stronger than frantic effort.",
    "Pick a start time and keep it as sacred as a meeting with someone you respect.",
    "A single clear intention can pull a scattered day together.",
    "Take the next step, then the next, without arguing with the staircase.",
    "Don't let urgent things bully the important ones.",
    "Start your session with a deep breath and an honest goal.",
    "Your attention is a kind of love. Give it wisely.",
    "Finish a thing today. Anything. Feel how good it is.",
    "Today's job is small, clear, and doable. Begin.",
  ],
  "bounce-back": [
    "The greatest weapon against stress is our ability to choose one thought over another.",
        "Let this be the day you try the easier version, and win.",
    "No one remembers the stumble if you keep moving with grace.",
    "A pause isn't a failure. It's a gathering of strength.",
    "The way back is shorter than the way you came.",
    "Keep your head up; the road bends in your favour.",
    "Heal first. The goals will wait.",
    "Learn, adjust, proceed.",
    "Every master has been through a thousand messy beginnings.",
    "Take one tiny action and let it count as a restart.",
    "You can take a break from your best and still be a person of your word.",
    "Maybe the plan changed. You didn't.",
    "Look at what survived, not only at what broke.",
    "A dented pot still holds soup.",
    "Make a small win right now: a glass of water, a made bed.",
    "It's okay that it didn't work. Now we know.",
    "You are still allowed to want it.",
    "Take the opportunity to rebuild it better.",
    "It was a rough day, not a rough life.",
    "Thank the setback for the clarity it gave.",
    "Look up. Look forward. Begin again.",
    "You can start your day at 3 pm if you need to.",
    "Roll the dice again. Skill improves the odds.",
    "Recovery is not laziness. It's strategy.",
    "Take a day for repair and call it progress.",
    "You aren't failing; you're figuring it out out loud.",
    "Hit refresh on your attitude and your plan.",
    "Remember how you bounced back last time? Do that.",
    "One bad decision doesn't define a good person.",
    "Nobody's perfect, and nobody's finished.",
    "There's strength in the third try, and wisdom in the fourth.",
    "You rise. Quietly, steadily, again.",
  ],
};

export const EN4 = build("en4", ROWS);
