import { build, type QuoteRows } from "./types";

/** Hinglish, part 1. Written for Sahil: warm, never preachy, and gentle enough for a low day. No authors. */
const ROWS: QuoteRows = {
  calm: [
    "Ek lamba saans lo. Abhi is pal mein sab theek hai.",
    "Sab kuch aaj hi nipta lena zaroori nahi hai. Kal bhi ek din hai.",
    "Thoda ruko. Chai pi lo. Duniya thodi der intezaar kar legi.",
    "Dimaag ka shor kam karne ka sabse aasaan tareeka hai: bas saans par dhyaan do.",
    "Jaldi nahi hai yaar. Dheere dheere bhi pahunch jaoge.",
    "Aaj ka din bas itna hi bada hai jitna agla ek ghanta.",
    "Kabhi kabhi kuch na karna bhi ek zaroori kaam hota hai.",
    "Kandhe dheele chhodo. Itne der se tight the.",
    "Har sawaal ka jawab abhi dena zaroori nahi hota.",
    "Shaant rehna kamzori nahi hai, ek hunar hai.",
    "Ghar jaisa sukoon dhoondho, chahe wo ek kone ki kursi hi kyun na ho.",
    "Aaj apni raftaar se chalo. Kisi se race nahi hai.",
    "Pehle apne aap ko thoda sa theek karo, phir baaki sab.",
    "Thoda paani pi lo. Aur ek lamba saans lo. Phir dekhte hain.",
    "Jab sab kuch tez ho, tum dheemi chaal chuno.",
    "Mann bhaari hai toh aaj list chhoti kar lo.",
    "Jo ho gaya, ho gaya. Abhi sirf is pal ko jee lo.",
    "Raat ko phone door rakh do. Neend bhi ek dawai hai.",
    "Aaj kisi ko kuch saabit nahi karna. Bas theek se rehna hai.",
    "Chhote chhote breaks lo. Dimaag ko bhi saans chahiye.",
    "Khidki ke paas baith kar baadal dekh lo. Ye bhi ek kaam hai.",
    "Sab kuch control mein nahi hota, aur ye bilkul theek hai.",
    "Aaj thoda halka chalo. Kal phir bhaari uthaa lena.",
    "Ek cheez ek samay par. Bas itna kaafi hai.",
    "Shaam ko din ko dheere se band karo, jaise koi kitaab.",
    "Jo kal ki chinta hai, wo kal ke liye rakh do.",
    "Dil ko samjhao: abhi koi emergency nahi hai.",
    "Saans andar, saans bahar. Aur kuch nahi karna is minute mein.",
    "Aaj ki sabse badi jeet: apne aap par gussa na karna.",
    "Sukoon wahin milta hai jahan tum jaldi nahi karte.",
    "Mann ko bhi nahlaao kabhi kabhi: sangeet, chai, ya chup.",
  ],
  courage: [
    "Dar lag raha hai? Theek hai. Phir bhi ek chhota kadam utha lo.",
    "Himmat ka matlab dar ka na hona nahi, dar ke saath chal dena hai.",
    "Jo kaam tum taal rahe ho, wo door se bada dikhta hai. Paas jaoge toh chhota lagega.",
    "Pehla kadam hamesha thoda ajeeb lagta hai. Phir bhi wahi sabse zaroori hai.",
    "Ek message bhej do. Ek call kar lo. Mushkil sirf shuruaat mein lagti hai.",
    "Tumne pehle bhi mushkil din kaate hain. Ye bhi nikal jayega.",
    "Galat hone ka dar rokta hai, par koshish karne se hi rasta banta hai.",
    "Sach bolna asaan nahi, par halka kar deta hai.",
    "Aaj apne aap se kaho: main try karunga, result jo bhi ho.",
    "Dar ko sath le lo, par steering apne haath mein rakho.",
    "Jis din tumne himmat ki, us din tumne apne aap ko chuna.",
    "Tum jitna sochte ho usse zyada bahadur ho.",
    "Naya kaam seekhna matlab thoda anari dikhna. Aur wahi sab se bada guts hai.",
    "Haath uthao, sawaal poochho. Samajhdaar log yahi karte hain.",
    "Ek chhoti si himmat roz, aur ek din tum alag insaan ho.",
    "Apni baat shaanti se kehna bhi ek bahaduri hai.",
    "Na kehne ki himmat bhi apni hoti hai. Use sambhaal ke rakho.",
    "Shuru karne ke liye perfect plan nahi chahiye, bas pehla step.",
    "Jo log aage nikle, wo pehle ghabrae the. Phir bhi chal diye.",
    "Aaj kuch aisa karo jo kal ke tum ko garv de.",
    "Tumhari awaaz kaanpe toh bhi bolo. Log sunenge.",
    "Haar ka darr tumhein jeet se door rakhta hai. Use thoda pichhe chhodo.",
    "Mushkil baat ko tab tak mat taalo jab tak wo bhaari na ho jaye.",
    "Apne sapne ko apne hi saamne bolo, phir doosron ke saamne.",
    "Tum mushkil se nikalne ka hunar jaante ho. Pehle bhi nikle ho.",
    "Dil thama ke ek bar aur try karo.",
    "Kabhi kabhi 'chalo dekhte hain' bhi sabse bahadur line hoti hai.",
    "Bina guarantee ke bhi shuruaat ki ja sakti hai.",
    "Aaj ek aisi cheez karo jisse thoda dar lage, par achha lage.",
    "Tum ready nahi ho, phir bhi shuru karo. Ready hona raaste mein aata hai.",
    "Apni kamzori chhupaane se zyada himmat use maan lene mein hai.",
  ],
  discipline: [
    "Aaj thoda hi sahi, par kiya toh sahi. Yahi progress hai.",
    "Mood ho ya na ho, das minute de do. Baaki apne aap chalega.",
    "Roz thoda sa kaam bade bade irade se behtar hai.",
    "Aaj ka kaam kal par mat daalo, par aaj ka thak jana bhi izzat se maan lo.",
    "Routine bori lagti hai, par wahi tumhari raftaar banati hai.",
    "Ek din ka kaam ek din mein. Bas wahi.",
    "Shuru karna sabse mushkil hissa hai. Isliye pehle woh nipta do.",
    "Jo roz karte ho, wahi tumhein banata hai.",
    "Aaj ka plan chhota rakho, par poora karo.",
    "Alarm bajne par uth jao, baat mat karo apne aap se.",
    "Jis din mann nahi karta, usi din ka kaam tumhein mazboot banata hai.",
    "Kal ki taiyari aaj raat hi kar lo. Subah halki lagegi.",
    "Chhote chhote wade apne aap se nibhao. Wahi bharosa banate hain.",
    "Itna mushkil nahi hai. Bas shuru kar do, phir chalta rahega.",
    "Ek achhi aadat dheere dheere ek achhi zindagi ban jaati hai.",
    "Aaj ka goal likho, aaj ka kaam karo, aaj ka din band karo.",
    "Pehle kaam, phir aaram. Aur aaram bhi bina guilt ke.",
    "Perfect nahi, par poora. Yahi aaj ka maqsad hai.",
    "Jab tak aadat nahi banti, bas lagataar aate raho.",
    "Mehnat dikhti nahi, par rang laati hai.",
    "Kal ka tumhara gussa aaj ka tumhara routine bana do.",
    "Bas panch minute. Fir dekhna kitna kuch ho jaata hai.",
    "Kaam ko chhote tukdon mein baanto. Har tukda ek jeet hai.",
    "Jaldi ka koi shortcut nahi hota, sirf lagataar mehnat hoti hai.",
    "Subah ka ek achha kaam poore din ka mood set kar deta hai.",
    "Mauka ka intezaar mat karo. Mauka banao.",
    "Thoda thoda karte raho. Ek din bahut kuch ho jayega.",
    "Jo aaj mushkil lagta hai, kal aadat lagega.",
    "Apne aap ko vaada do, aur use nibhao. Wahi asli confidence hai.",
    "Aaj ke din ko kal ki shikayat mat banne do.",
    "Roz ka chhota step, ek din ka bada safar.",
    "Mehnat ke saath aaram bhi seekho. Dono milke kaam karte hain.",
  ],
  hope: [
    "Ye daur bhi guzar jayega. Har mausam guzarta hai.",
    "Raat jitni bhi lambi ho, subah zaroor aati hai.",
    "Abhi jo hai, wahi sab kuch nahi hai. Kahani aage bhi chalegi.",
    "Achhe din kisi calendar ke bharose nahi aate, par aate zaroor hain.",
    "Kuch achha tumhari taraf badh raha hai, shayad tumhein pata bhi nahi.",
    "Aaj ek chhoti si umeed rakh lo. Wo kaafi hai.",
    "Jo bijh tumne boya hai, wo mitti ke neeche mehnat kar raha hai.",
    "Ye chapter mushkil hai, par poori kitaab nahi.",
    "Kal ka din aaj se behtar ho sakta hai. Bas aaj thoda sambhal lo.",
    "Raste band lagte hain, jab tak mod nahi dikhta.",
    "Har mushkil ke baad kuch seekhne ko milta hai, aur kuch aasaan bhi.",
    "Tumhari mehnat bekaar nahi ja rahi, bas dikh nahi rahi.",
    "Thoda aur ruko. Baadal chhatne wale hain.",
    "Dil se umeed rakho. Kabhi kabhi universe bhi sunta hai.",
    "Aaj raat mushkil hai, par subah mein ek naya mauka hoga.",
    "Jo gaya wo gaya. Jo aane wala hai wo tumhare haath mein hai.",
    "Ek achha phone call, ek achhi khabar. Kuch bhi ek din mein badal sakta hai.",
    "Aaj nahi, toh kal. Kal nahi, toh parso. Koshish ruki nahi toh sab theek hoga.",
    "Tumhare liye kuch achha likha ja chuka hai. Bas agla panna palatna hai.",
    "Jo abhi nahi hua, wo shayad aur behtar tareeke se hone wala hai.",
    "Hum sab kisi na kisi mod par phanste hain, aur phir nikal jaate hain.",
    "Din chhote hote hain, par umeed lambi hoti hai.",
    "Tum akele nahi ho. Kai log tumhare liye achha chahte hain.",
    "Tumhari kahani abhi bachi hui hai. Aur achhi bhi hogi.",
    "Dheere dheere sab theek ho jaata hai, jab tum chalte rehte ho.",
    "Aaj ek chhota achha pal dhundh lo. Wo kal ka sahara banega.",
    "Bahut kuch achha hone wala hai, bas dhairya rakho.",
    "Baarish ke baad hamesha dhoop nikalti hai.",
    "Tumhari mehnat ka phal der se aata hai, par meetha aata hai.",
    "Is mod ke baad shayad seedhi sadak hai.",
    "Thodi hasi, thodi umeed. Aur kya chahiye shuru karne ko?",
    "Aaj ka din bhi ek mauka hai.",
  ],
  "self-worth": [
    "Tum jaise ho, waise bhi kaafi ho.",
    "Dusron se compare mat karo. Tumhari raftaar tumhari apni hai.",
    "Tumhari keemat tumhare kaam se nahi, tumhare hone se hai.",
    "Aaj kam kiya toh bhi theek. Tum insaan ho, machine nahi.",
    "Apne aap se waise baat karo jaise apne sabse achhe dost se karte ho.",
    "Tum ne bahut kuch jhela hai, aur phir bhi yahan ho. Ye chhoti baat nahi.",
    "Tum late nahi ho. Tum apne time par ho.",
    "Galti ho gayi toh tum bure nahi ho gaye.",
    "Tumhari koshish dekhne wale bahut hain, chahe tumhein pata na ho.",
    "Aaj apne aap ko ek chhota sa shukriya bol do.",
    "Tum kisi ki bhi tarah bante ho, par tumhari tarah koi nahi.",
    "Tumhari mehnat ki izzat karo, chahe kisi ne taali na bajai ho.",
    "Aaram karna tumhara haq hai, inaam nahi.",
    "Jis din kuch nahi hua, us din bhi tum kaafi the.",
    "Apne aap par thoda rehem karo. Tum pehle se hi bahut koshish kar rahe ho.",
    "Tumhari awaaz, tumhari soch, tumhari jagah: sab kuch maayne rakhta hai.",
    "Kisi ke 'kam' kehne se tum kam nahi ho jaate.",
    "Apni chhoti jeet ko bhi manao. Wo tumhari hai.",
    "Tumne jo seekha hai, wo koi aur nahi jaanta.",
    "Tum jaisa koi doosra nahi, aur wahi tumhari taqat hai.",
    "Kabhi kabhi sirf aage badhte rehna hi sabse badi baat hoti hai.",
    "Tumhare andar achhai ki bahut jagah hai.",
    "Khud ko maaf karna seekho. Wo ek zaroori hunar hai.",
    "Apne aap par bharosa rakho, jab koi aur na kare tab bhi.",
    "Jo log tumhein pasand karte hain, wo tumhara asli roop pasand karte hain.",
    "Tum kisi ke liye bojh nahi ho.",
    "Aaj apne aap ko wahi pyaar do jo tum doosron ko dete ho.",
    "Tumhari kahani kisi aur ki kahani se halki ya bhaari nahi, bas alag hai.",
    "Thoda sa garv kar lo, tumne kaafi kuch kiya hai.",
    "Tum bahut kuch ho, bas aaj thak gaye ho.",
    "Tumhare hone se kisi ka din achha ho sakta hai. Shayad aaj hi.",
  ],
  gratitude: [
    "Aaj ke din ki ek achhi cheez dhundho. Hamesha ek hoti hai.",
    "Chai ki pehli chuski aur ek sukoon ka pal. Shukriya, aaj ke liye.",
    "Un logon ko yaad karo jo bina kahe tumhare saath rahe.",
    "Jo tumhare paas hai, kisi ki dua ho sakti hai.",
    "Aaj kisi ko dil se thank you bol do.",
    "Subah uthe, saans li, ek aur din mila. Ye bhi kuch kam nahi.",
    "Ghar ka khaana aur ghar ke log: badi nemat hai.",
    "Un mushkil dinon ka bhi shukriya jinhone tumhein mazboot banaya.",
    "Ek achha dost ek khazana hai. Use batao ki wo kitna zaroori hai.",
    "Aaj jo kuch bhi achha hua, usse rukkar ek baar mehsoos karo.",
    "Maa ke haath ka khaana, dost ki hasi, apni chhat. Sab kuch yaad rakho.",
    "Shukriya karna bhi dil ko halka kar deta hai.",
    "Jo log tumhari madad karte hain, unhein yaad rakhna.",
    "Khudko bhi thank you bolo, tumne aaj bhi try kiya.",
    "Ek simple sa din bhi ek bahut badi baat hai.",
    "Sone ki jagah, pani, roshni: sab nemat hain.",
    "Kisi ki chhoti si madad bhi bada fark laati hai. Yaad rakho.",
    "Rukkar dekho: tumhare paas kitna kuch hai jo tumne maanga tha.",
    "Aaj raat sone se pehle teen achhi cheezein soch lo.",
    "Dil se kahi hui ek 'shukriya' ki line se rishte mazboot hote hain.",
    "Un logon ko yaad karo jinhone tumhein pehle mauka diya.",
    "Aaj ka mausam, aaj ka khaana, aaj ka saath: sab ek tohfa hai.",
    "Thoda sa shukra kar lo, dil halka ho jayega.",
    "Jo mil gaya, usse kadar karo. Jo nahi mila, uska bhi koi matlab hoga.",
    "Dost se mile huye do minute bhi din badal dete hain.",
    "Jis chhoti cheez ne tumhein aaj hasaya, use yaad rakhna.",
    "Apne parivaar ke liye ek pal shukriya mehsoos karo.",
    "Shukriya ek aadat hai. Roz thoda sa kar lo.",
    "Purane dino ki yaadein bhi ek khazana hain.",
    "Aaj ki raat ek shukriya ke saath khatam karo.",
    "Tumhein sunne wale ek insaan ka bhi shukriya karna.",
  ],
  focus: [
    "Ek kaam ek baar mein. Baaki sab thoda intezaar kar sakte hain.",
    "Phone ko ulta rakh do. Jo zaroori hai wo wapas aa jayega.",
    "Sabse zaroori kaam pehle. Baaki kaam apne aap line mein lag jayenge.",
    "Dhyaan wahin jaata hai jahan tum le jaate ho.",
    "Das minute ka timer lagao aur sirf ek kaam karo.",
    "Do cheezein chhodo, ek cheez pakdo.",
    "Dimaag ke tabs band karo. Ek hi tab kholo.",
    "Jo kaam tum taal rahe ho, wahi pehle karo.",
    "Dhyaan bhatak jaye toh gussa mat ho, bas wapas aa jao.",
    "Aaj ka sabse zaroori kaam kaun sa hai? Wahin se shuru karo.",
    "Kam notifications, zyada dhyaan.",
    "Pehle kaam ko ek chhote step mein tod do.",
    "Thodi der ke liye duniya ko mute kar do.",
    "Perfect shuruaat ka intezaar mat karo. Ganda draft bhi draft hai.",
    "Jo kaam ek ghante mein ho sakta hai, usse poora din mat do.",
    "Dhyaan ek muscle hai. Roz thoda sa karo, mazboot hoga.",
    "Table saaf karo, dimaag bhi saaf hoga.",
    "Pehle teen kaam chuno. Baaki sab bonus hai.",
    "Aaj ka goal likh lo. Likha hua goal yaad rehta hai.",
    "Thodi der ki gehri mehnat poore din ki halki hadbadi se behtar hai.",
    "Aaj ek kaam dil laga ke karo, aur use poora karo.",
    "Zaroorat ke hisaab se 'na' bolna seekho.",
    "Dhyaan ko pyaar se kaam par laao, zabardasti se nahi.",
    "Ek chhoti list, ek bada fark.",
    "Pehle saans, phir plan, phir kaam.",
    "Kaam mein doob jao, time khud nikal jayega.",
    "Jo ruka hua hai, uska pehla chhota step aaj hi uthao.",
    "Dhyaan kharab ho gaya? Paani piyo, tehel lo, wapas aa jao.",
    "Aaj ke din ka ek hi star: ek poora kaam.",
    "Kaam shuru karne ka ek chhota ritual banao: chai, desk, saans, shuru.",
    "Thoda focus, thoda break, phir thoda focus. Yahi formula hai.",
  ],
  "bounce-back": [
    "Aaj gir gaye? Koi baat nahi. Uthne ka mauka aaj bhi hai.",
    "Ek kharab din poori kitaab nahi hota.",
    "Kal chhoot gaya, aaj phir se shuru. Koi speech ki zaroorat nahi.",
    "Galti se seekho, usse chipko mat.",
    "Streak toot gayi? Tum nahi toote.",
    "Wapas aana bhi himmat ka kaam hai.",
    "Fail hona matlab ek aur tareeka pata chal gaya jo kaam nahi karta.",
    "Chhoti shuruaat se hi badi wapsi hoti hai.",
    "Aaj ka plan halka kar do. Par shuru zaroor karo.",
    "Gir ke uthna zindagi ka hissa hai, kamzori nahi.",
    "Pichhli baar jo hua usse darna nahi, usse seekhna hai.",
    "Tumne pehle bhi wapsi ki hai. Phir kar sakte ho.",
    "Aaj ka din saaf slate hai. Kal ka hisaab nahi poochta.",
    "Thoda rukna aur phir chalna, dono progress hain.",
    "Plan bigad gaya? Chhota plan banao.",
    "Aaj jo hua, use aaj chhod do. Kal naya hai.",
    "Haar ek pal ki hoti hai. Aadat nahi.",
    "Dobara try karna sabse bada iraada hai.",
    "Bura waqt hamesha kuch sikhata hai, chahe tumhein achha na laga ho.",
    "Mushkil se nikle ho pehle bhi, aaj bhi nikal jaoge.",
    "Jab sab kuch ulta lage, tab chhota sa seedha kaam kar lo.",
    "Din kharab gaya toh shaam ko sudhaar lo.",
    "Aaj nahi hua? Koi baat nahi. Kal ke liye thoda sa tayyar ho jao.",
    "Girne ka matlab hai tum chal rahe the.",
    "Apne aap ko doosra mauka do. Tum uske haqdaar ho.",
    "Ruko, saans lo, wapas chalo.",
    "Dhool jhaado, aage badho.",
    "Tumhari galti tumhari pehchaan nahi hai.",
    "Kuch din dheere hote hain. Wo bhi aage ke hi din hote hain.",
    "Shuruaat kabhi bhi ho sakti hai, subah ho ya shaam.",
    "Himmat mat haaro. Bas rasta badal lo.",
    "Wapsi bhi ek jeet hai.",
  ],
};

export const HI1 = build("hi1", ROWS);
