import { build, type QuoteRows } from "./types";

/** Hinglish, part 2: work, learning, job hunt, long days. No authors. */
const ROWS: QuoteRows = {
  calm: [
    "Office ka stress ghar tak mat laao. Darwaze par chhod do.",
    "Email baad mein bhi khul jayega. Pehle chai.",
    "Jab kaam bahut ho, tab ek minute ruk kar saans lena sabse smart move hai.",
    "Deadline ke saath dosti karo, dushmani nahi.",
    "Lunch break ko poora jee lo. Wo bhi kaam ka hissa hai.",
    "Aaj meeting ke baad thodi der chup baith lo.",
    "Dheere dheere sab nipta lenge. Abhi bas agla step.",
    "Pehle apna dimaag shaant karo, phir kaam ko ghere.",
    "Ek achha break poore ghante ka kaam sudhaar deta hai.",
    "Kaam ke beech mein bhi thodi si shanti dhundh lo.",
    "Ghadi ko mat dekho. Kaam ko dekho.",
    "Kaam ke baad ka waqt tumhara apna hai. Use bachao.",
    "Chinta list se kaam nahi hota. Ek line likho aur shuru karo.",
    "Dil ko samjhao: tum sab kuch ek saath nahi nipta sakte, aur zaroorat bhi nahi.",
    "Aaj ka kaam halka rakho, aur use shaanti se poora karo.",
    "Thoda sa paida hua tension bhi ek lambi saans se kam ho jata hai.",
    "Kabhi kabhi kuch na bolna sabse samajhdaar jawab hota hai.",
    "Shaam ko screen band karo aur khidki se bahar dekho.",
    "Apni desk par ek chhota sa sukoon ka kona bana lo.",
    "Subah jaldi uth kar pehle paanch minute sirf apne liye lo.",
    "Jo cheez control mein nahi, uski fikr chhod do.",
    "Mann ko thoda khali karo, phir naya kaam bharo.",
    "Raaste mein chalte hue gaana sun lo. Din halka lagega.",
    "Nahane se, chai se, ya chup se: koi bhi reset button chun lo.",
    "Weekend ko weekend rehne do. Thoda sa kuch kam kar lo.",
    "Kuch cheezein sirf dheeraj se theek hoti hain.",
    "Naye din mein sab kuch dheere se shuru hota hai.",
    "Din bhar ki bhaag daud ke baad, ghar ek shaanti lagta hai.",
    "Sochna band karo, bas ek kaam par haath rakh do.",
    "Jab kuch samajh na aaye, thoda tehal lo.",
    "Tension aati hai aur jaati hai. Tum wahi rehte ho.",
  ],
  courage: [
    "Interview ke pehle ghabrahat hoti hai. Iska matlab hai tumhein parwaah hai.",
    "Apply kar do. Jawab 'nahi' bhi aaya toh kuch seekh lenge.",
    "Seekhna shuru karna hi sabse bada step hai, chahe sab kuch naya lage.",
    "Jab tak koshish nahi karoge, 'nahi' ka matlab nahi pata chalega.",
    "Ek aur application bhej do. Ek aur sawaal poochh lo.",
    "Naya tool seekhna dar lagta hai, par wahi tumhein aage le jayega.",
    "Apne kaam ko dikhane se mat daro. Wahi tumhari pehchaan banega.",
    "Boss ko apni baat batane ki himmat karo.",
    "Pehle thoda ajeeb lagega, phir aadat ho jayegi.",
    "Tum jitna bhi seekh lo, kuch naya hamesha reh jata hai. Aur ye achha hai.",
    "Resume mein khali jagah dekh kar mat ghabrao. Tum aage ki kahani likh rahe ho.",
    "Mushkil project sab ko darata hai. Tum bas pehla chhota hissa shuru karo.",
    "Naye logon se milna thoda ghabra deta hai, par wahi darwaze kholta hai.",
    "Jab apni baat rakhte ho, tab hi to log tumhein jaan paate hain.",
    "Apne kaam par bharosa karo, aur use bhej do.",
    "Mushkil sawaal poochho. Wahi seekhne ka sabse tez raasta hai.",
    "Tum try karte rahoge toh ek din 'yes' zaroor milega.",
    "Galti hone ka dar mat rakho. Seekhne walon se hi galtiyan hoti hain.",
    "Kal ka interview aaj ki taiyari par depend karta hai. Ek kadam karke taiyari karo.",
    "Dikhna chahiye ki tum koshish kar rahe ho. Result baad mein aata hai.",
    "Pehle project mein bhi darr tha. Ab ye normal lagta hai. Isi tarah badhte hain.",
    "Apni himmat chhoti rakhna theek hai, bas roz rakhna.",
    "Jab 'main nahi kar sakta' aaye, usme 'abhi tak' jod do.",
    "Kuch naya seekhne ka dar, naye mauke ka sabse sahi sanket hai.",
    "Public mein bolna mushkil hai, par har baar thoda aasaan hota hai.",
    "Jo kaam tumhein darata hai, use subah sabse pehle karo.",
    "Dekho kitna badh gaye ho, ek saal pehle ye kaam ho hi nahi sakta tha.",
    "Pooch lo. Bol do. Bhej do. Tumne socha tha usse kam bura hoga.",
    "Dusron ki raay se zyada apne sapne ki awaaz suno.",
    "Dar ke pichhe aksar wahi cheez hoti hai jo tum chahte ho.",
    "Aaj ek aisa kaam karo jo tum kal tak taal rahe the.",
  ],
  discipline: [
    "Power BI ka ek chhota dashboard roz. Ek mahine mein tum alag insaan ho.",
    "Aaj ka session chhota ho toh bhi karo. Streak dil ki hoti hai, ghadi ki nahi.",
    "Meditation ke das minute: sabse sasta aur sabse accha investment.",
    "English roz thodi thodi padho. Do mahine baad awaaz badal jayegi.",
    "Job prep aaj bhi zaroori hai. Ek hi question solve karo, par karo.",
    "Seekhna kal ke liye nahi, aaj ke liye hota hai.",
    "Practice karte raho, perfect hona zaroori nahi.",
    "Aaj ka revision kal ki confidence banata hai.",
    "Mock interview do ya khud se, par do.",
    "Likh ke seekho. Dobara likhoge toh pakka yaad rahega.",
    "Jo bhi seekha, ek line mein likh do. Ek mahine mein poori kitaab ban jayegi.",
    "Study ka time fix karo aur use appointment ki tarah nibhao.",
    "Aaj ka concept aaj hi samajh lo. Kal ka bhaar halka rahega.",
    "Kuch na samajh aaye toh bhi baitho. Samajh baithne se aati hai.",
    "Roz ek sawaal solve karna, ek mahine mein tees sawaal hain.",
    "Pehle sabse mushkil topic, jab dimaag fresh ho.",
    "Coding hai, Excel hai, ya reading: roz thoda sa karo.",
    "Notes banao, par unhe dobara dekhna mat bhoolo.",
    "Seekhne ka ek hi formula hai: roz, chhota, aur dhyaan se.",
    "Aaj ka kaam utna hi ho jitna ho sake, par ho zaroor.",
    "Jis topic se bachte ho, wahi tumhari sabse badi kamzori aur sabse badi jeet hai.",
    "Samay nikaalna nahi padta, samay banana padta hai.",
    "Application bhejna bhi ek session hai. Roz ek bhejo.",
    "Kaam par laut aao jab mann bhatak jaye. Aise hi discipline banta hai.",
    "Chhoti si practice bhi practice hai.",
    "Padhai ke beech mein phone door rakh do. Dono ka bhala hoga.",
    "Roz utna hi karo jitna kal bhi kar sako.",
    "Tez nahi, lagataar chalo.",
    "Aaj ka effort kal ka result hai. Thoda sa dhyaan do.",
    "Jis din mann nahi hai, us din sabse chhota version kar lo.",
    "Seekhne wale ko samay nahi, niyam chahiye.",
    "Roz ki chhoti mehnat ek din badi pehchaan banegi.",
  ],
  hope: [
    "Jo mehnat abhi dikh nahi rahi, wo andar andar kaam kar rahi hai.",
    "Ek offer, ek call, ek mauka: kuch bhi kal aa sakta hai.",
    "Tumhari naukri ka sahi mauka bhi kahin tumhari taraf aa raha hai.",
    "Jo seekha hai wo ek din tumhein bahut aage le jayega.",
    "Har reject mail ek 'haan' ke kareeb le jati hai.",
    "Abhi sirf shuruaat hai, aur shuruaat mein sab dheere lagta hai.",
    "Tumhare hunar ko koi na koi zaroor pehchanega.",
    "Ek achhi tareekh hamesha aati hai. Aaj nahi, toh kal.",
    "Jo raasta abhi dhundla hai, usme kuch door jaakar roshni hai.",
    "Naye saal tak tum aaj ke tum se bahut aage honge.",
    "Kuch din mushkil hote hain, par saal tumhare hi hota hai.",
    "Tum jo kar rahe ho, uska phal zaroor milega.",
    "Naye mauke aksar purane mushkil dinon ke baad aate hain.",
    "Kal ki fikr mat karo, kal bhi tumhare saath hai.",
    "Aaj ki mehnat aane wale kal ka vaada hai.",
    "Sabr rakho. Sab theek hoga. Dheere dheere.",
    "Jo log tumhein achhi tarah jaante hain, wo tumhare liye khush honge.",
    "Tumhari mehnat ek din tumhein naam degi.",
    "Ek achha mauka kab, kahan se aa jaye, kisi ko nahi pata.",
    "Tum raaste mein ho, bas manzil door lagti hai.",
    "Har seekhne wale ko ek din waqt mil jata hai.",
    "Pehle andhera hota hai, phir sab clear hota hai.",
    "Aaj kuch bhi ho, kal ke liye umeed zinda rakho.",
    "Ye mushkil daur ek din ek kahani ban jayega.",
    "Tum ek dum sahi raaste par ho, bas aaj thoda thak gaye ho.",
    "Naya projects, naye log, naye mauke: sab kuch aage hi hai.",
    "Waqt lagta hai, par achha waqt aata hai.",
    "Har din ek naya mauka lekar aata hai.",
    "Kal kuch achha ho sakta hai. Isliye aaj thoda tik jao.",
    "Aane wale mahine mein tum aaj ke baare mein muskura ke baat karoge.",
    "Hum sab dheere dheere kahin pahunchte hain.",
  ],
  "self-worth": [
    "Naukri nahi mili toh tum kam nahi ho. Wo bas ek rasta band hua.",
    "Rejection tumhari value nahi, kisi ki zaroorat ka match hai.",
    "Tum seekh rahe ho. Ye apne aap mein ek badi baat hai.",
    "Tumhare skills tumhari mehnat ka saboot hain.",
    "Aaj productive nahi rahe? Tum phir bhi kaafi ho.",
    "Tum ek insaan ho, sirf ek resume nahi.",
    "Tumhari value kisi interview ke result se nahi tay hoti.",
    "Tum jitna kar rahe ho, usse zyada kar chuke ho.",
    "Aaj ka kaam chhota ho, par tumhara mann bada hai.",
    "Doosre kya kar rahe hain, usse tumhara safar chhota nahi hota.",
    "Apne aap ko ek 'achha kiya' bol do.",
    "Tumhari mehnat dekhne wale kuch log zaroor hain.",
    "Tum apni zindagi ke sabse achhe project ho.",
    "Tum kisi se kam nahi, kisi se zyada bhi nahi. Bas tum ho, aur wahi kaafi hai.",
    "Jo seekh rahe ho, usme tumhari pehchaan bandh rahi hai.",
    "Naye logon ke beech bhi tumhari jagah hai.",
    "Gussa mat ho apne aap par. Tum thake hue ho, kamzor nahi.",
    "Tumhari lagan hi tumhari sabse badi degree hai.",
    "Har din ek tum ko thoda aur behtar banata hai.",
    "Tum uski izzat ke laayak ho jo tumne mehnat se banaya hai.",
    "Kisi ka 'na' tumhari kahani ka aakhri panna nahi hai.",
    "Aaj kisi ne tumhari tareef nahi ki toh khud kar lo.",
    "Tumhari mehnat ki keemat hai, chahe koi kitna bhi kam aanke.",
    "Tum apne kaam se pyaar karte ho, aur ye bahut khoobsurat baat hai.",
    "Tum apni raftaar ke maalik ho.",
    "Tumhein sab kuch aaj hi nahi aana chahiye. Seekhne ke liye saal hote hain.",
    "Jo tum aaj ho, wo kal ke tum se behtar hai.",
    "Tumhare sapne chhote nahi, bas abhi door hain.",
    "Apne aap par bharosa rakho, jab koi aur dekh na raha ho.",
    "Tum kisi aur ki tarah bante nahi, tum apni tarah bante ho.",
    "Tum sirf kaam se nahi, apne vyaktitva se bhi pehchane jaate ho.",
  ],
  gratitude: [
    "Jis ne tumhein kuch seekhaya, use dil se yaad karo.",
    "Naukri hai, ya naukri ki talaash: dono mein tumhare saath log hain. Shukriya.",
    "Ek mentor, ek senior, ek dost: sabka shukriya karna.",
    "Aaj ka kaam jo ho gaya, uska bhi thoda shukriya.",
    "Tumhari mehnat ko jo dekhta hai, usse kabhi kabhi thank you bol do.",
    "Zindagi ne tumhein pehle bhi sambhala hai. Aaj bhi sambhal rahi hai.",
    "Ghar se door hone par ghar ki yaad aati hai, aur wo bhi ek nemat hai.",
    "Thoda sa waqt jo apna hai, uska shukriya.",
    "Jab koi tumhari baat dhyaan se sune, use thank you bolna.",
    "Kaam ke beech chai ka ek cup aur ek muskurahat: shukriya.",
    "Un dinon ko yaad karo jab tum yahan tak pahunchna chahte the.",
    "Aaj kuch seekha? Uska shukriya.",
    "Un logon ko yaad karo jinhone tumhein seekhne diya.",
    "Dil se shukriya kehne wale log kabhi akele nahi hote.",
    "Teacher, senior, ya internet par koi anjaan: jisne tumhari madad ki, uska shukriya.",
    "Jis kaam se tumhein roti milti hai, uski izzat karo.",
    "Mushkil din bhi ek sabak the. Shukriya, unke liye bhi.",
    "Subah ki dhoop, shaam ki chai. Ye sab muft ki khushiyan hain.",
    "Kisi ne tumhein kuch seekhaya? Aaj usse bol do.",
    "Tumhare dost jo tumhari baat sunte hain, unhein bata do ki tum unhein maante ho.",
    "Aaj raat sone se pehle ek achhi cheez ko yaad karna.",
    "Zindagi mein jo log hain, unhein kabhi kabhi bata dena chahiye.",
    "Shukriya karo un dino ka jinhone sabr sikhaya.",
    "Aaj jo kuch tumhare paas hai, wo kabhi tumhari list mein tha.",
    "Chhoti si madad bhi bada shukriya maangti hai.",
    "Is mehnat ka shukriya jo tumne aaj ki.",
    "Aaj ke din ko thanks bol do.",
    "Kuch log bina batae tumhara din behtar bana dete hain. Unhein yaad karo.",
    "Tumhare saath khade rehne wale logon ko shukriya.",
    "Halki si thakaan bhi tabhi hoti hai jab tumne kuch kiya ho. Shukriya.",
    "Kisi ek aadmi ka shukriya karna: ye kaam aaj hi kar do.",
  ],
  focus: [
    "Meeting ke baad turant ek next step likh lo.",
    "Naye kaam ko chhote chhote hisson mein bata do. Shuru karna aasaan ho jayega.",
    "Dopahar mein ek ghante ka deep work: phone door, sirf kaam.",
    "Pehle woh karo jo ruka hua hai.",
    "Ek tab, ek task, ek chai.",
    "Aaj teen kaam ya ek poora kaam. Chuno aur nibhao.",
    "Excel ya Power BI khol ke sirf ek chart banao. Bas.",
    "Notification band, dhyaan chalu.",
    "Pehle kaam ka maqsad likho, phir kaam karo.",
    "Dhyaan kharab hone par kaam chhota kar do, chhodo mat.",
    "Jo kaam 'jaldi' lagta hai, wo aksar 'zaroori' nahi hota.",
    "Pehle teen minute sirf plan banao. Phir kaam shuru.",
    "Aaj sirf ek cheez achhi tarah seekho.",
    "Kaam ke beech mein khud ko roko mat. Bas rasta dekhte raho.",
    "Mushkil sawal ko chhote sawalon mein tod do.",
    "Padhai ya kaam: pehle desk saaf karo.",
    "Do ghante ka kaam ek ghante mein ho jata hai jab phone door ho.",
    "Dhyaan dhyaan se aata hai: roz thoda abhyas karo.",
    "Aaj ke din ka ek hi star: kaam jo sabse zaroori hai.",
    "Ek kaam khatam hone par ek chhoti si khushi manao.",
    "Kabhi kabhi 'baad mein' ka matlab 'kabhi nahi' hota. Zaroori kaam abhi karo.",
    "Kaam shuru karo bina reply kiye ki 'kaise hoga'.",
    "Likhne se dimaag saaf hota hai: teen line likh lo.",
    "Pehle sabse boring kaam. Phir aaram se baaki.",
    "Apne kaam ko ek naam do: 'Aaj ka ek kaam'.",
    "Poora dhyaan ek ghante ke liye. Sirf ek ghante.",
    "Kaam se pehle paani, kaam ke baad paani.",
    "Jo cheez dhyaan tod rahi hai, use pehchaano aur door karo.",
    "Dhyaan dene wale ko kuch bhi mushkil nahi.",
    "Ek poora kaam finish karna, das adhoore kaamon se behtar hai.",
    "Kaam ko aadhe mann se mat karo; ya poore mann se karo ya thoda ruko.",
  ],
  "bounce-back": [
    "Interview kharab gaya? Ek lamba saans lo. Agla behtar hoga.",
    "Rejection email aayi? Padho, sambhalo, aage badho.",
    "Aaj kuch seekh nahi paye? Kal phir try karenge.",
    "Test mein number kam aaye toh bhi tumhari mehnat bekaar nahi gayi.",
    "Ek galat kaam poore career ko define nahi karta.",
    "Project atak gaya? Pehle kadam se phir shuru karo.",
    "Bug mil gaya? Matlab tum kuch bana rahe ho.",
    "Fail hona seekhne ka hissa hai.",
    "Jab kaam na chale, tab ek chhoti si jeet dhundho.",
    "Tum pehle bhi wapas aaye ho. Phir aa sakte ho.",
    "Dobara apply karo. Dobara prepare karo. Dobara try karo.",
    "Haar se seekho, haar mein mat baitho.",
    "Aaj kuch bhi nahi hua? Kal ek chhota sa step hi sahi.",
    "Hafta kharab gaya toh agla hafta naya hai.",
    "Pichhli galti ko apna teacher bana lo.",
    "Dil dukha hai? Thoda aaram karo, phir aage badho.",
    "Kaam ruka hua hai? Ek kaam chhota karke dekho.",
    "Aaj thak gaye ho, kal thoda halka karna.",
    "Poora din kharab nahi hota, bas ek hissa hota hai.",
    "Mushkil din ke baad ki chai sabse achhi lagti hai.",
    "Tum rukte nahi ho, bas kabhi kabhi saans lete ho.",
    "Plan B bhi ek plan hota hai, aur kai baar behtar bhi.",
    "Galat mod se bhi sahi jagah pahunchne ka rasta nikal sakta hai.",
    "Fir se shuru karna bhi ek taakat hai.",
    "Jo kuch toot gaya, uske tukdon se naya bana sakte ho.",
    "Aaj bura din tha, par tum bure nahi ho.",
    "Dobara khade ho jao. Is baar thoda aur samajhdaari ke saath.",
    "Gir kar uthne wale ko hi chalna aata hai.",
    "Koi baat nahi, ek aur try.",
    "Kal tumne jo nahi kiya, aaj uska sirf ek hissa kar lo.",
    "Mushkil aaye toh yaad rakho: ye bhi seekhne ka ek hissa hai.",
    "Behtar hone ke liye pehle thoda kharab hona padta hai.",
  ],
};

export const HI2 = build("hi2", ROWS);
