import { build, type QuoteRows } from "./types";

/** Hinglish, part 3: body, family, friends, evenings, low days. No authors. */
const ROWS: QuoteRows = {
  calm: [
    "Raat ko din ka bojh bistar tak mat le jao.",
    "Thodi der khamoshi se baith jao. Khamoshi bhi baat karti hai.",
    "Gunguna lo ek purana gaana. Mann halka ho jayega.",
    "Chhat par jao, aasmaan dekho. Tumhari chinta chhoti lagegi.",
    "Chai banao, khidki kholo, aur kuch mat socho.",
    "Aaj raat jaldi so jao. Kal ke tum ko aaram mil jayega.",
    "Dimaag mein jo shor hai, use ek page par utaar do.",
    "Garam paani se haath dho lo. Chhota sa reset hai.",
    "Sukoon kabhi kabhi ek khaali kamre mein hota hai.",
    "Jo log tumhein shaant rakhte hain, unke saath waqt bitao.",
    "Gehri saans: andar char, bahar chhe. Teen baar karo.",
    "Dheere se kuch khaao, dheere se chalo, dheere se socho.",
    "Aaj shaam kuch bhi plan mat karo.",
    "Pet bhara ho, dil halka ho: aur kya chahiye?",
    "Kuch din bas guzarne hote hain, aur wo bhi theek hai.",
    "Baarish ki awaaz sunna bhi ek dhyaan hai.",
    "Din bhar ki thakaan ko ek dheeme gaane mein ghol do.",
    "Neend aa rahi hai toh so jao. Duniya kal bhi wahin hogi.",
    "Dhyaan do: tumhare kandhe bahut upar the. Neeche karo.",
    "Dil ko samjhao ki sab kuch abhi theek karna zaroori nahi.",
    "Thodi si dhoop, thodi si hawa, thodi si chup.",
    "Aaj ka din bhaari tha, par raat halki ho sakti hai.",
    "Chhote chhote pal bhi sukoon de sakte hain.",
    "Sar dard ho toh paani piyo, screen band karo, aankhein band karo.",
    "Jab sab shor kare, tum chup rehkar jeeto.",
    "Ek achhi neend sab kuch thoda halka kar deti hai.",
    "Dheere se saans lo. Tumhein kahin pahunchna nahi hai.",
    "Raat ka aasmaan bhi dheere dheere chalta hai.",
    "Khud ko thoda sa aaraam do. Tumne kamaya hai.",
    "Aaj ke hisse ka kaam ho gaya. Ab chhodo.",
    "Shaanti ek faisla hai. Aaj use chun lo.",
  ],
  courage: [
    "Kisi ko 'sorry' bolna aur 'thank you' bolna: dono mein himmat lagti hai.",
    "Apne dost ko call karo jise bahut din se nahi kiya.",
    "Ghar mein sach baat kehna mushkil lagta hai, par rishta mazboot karta hai.",
    "Madad maangna kamzori nahi, samajhdaari hai.",
    "Tum akele dar rahe ho, par tum akele nahi ho.",
    "Dil ki baat kehne ka dar kabhi kabhi baat se bhi bada hota hai.",
    "Gym ya walk par chalo. Pehla din sabse mushkil hota hai.",
    "Naye logon se milo. Kabhi kabhi ek hi mulaqat sab badal deti hai.",
    "Apni feelings ko naam do. Wo kam daraavni lagengi.",
    "Kisi ko 'main tumse pyaar karta hoon' kehna bhi himmat hai.",
    "Jab sab chup ho, tum sach bol do.",
    "Jo log tumhein neecha dikhate hain, unse door chalo.",
    "Apni jagah banane ke liye kabhi kabhi jagah chhodni padti hai.",
    "Tum rote ho toh bhi theek hai. Rone ke baad bhi chalna aata hai.",
    "Kal ki baat aaj kehni padegi, kal tak intezaar mat karo.",
    "Dil se jeene ke liye thoda risk lena padta hai.",
    "Haan kehne ki himmat bhi hoti hai, na kehne ki bhi.",
    "Aaj apne dil ki sunne ki himmat karo.",
    "Pehle apne aap se sach bolo.",
    "Aaj kisi ko maaf karne ki himmat karo. Ya apne aap ko.",
    "Naye shehar, naye log, nayi aadatein: sab shuru mein ajeeb, phir apna.",
    "Jo kuch tumne socha hai use kehne ka tareeka dhoondho, na ki chup rehne ka bahana.",
    "Tum jitna sochte ho, log tumhein utna judge nahi karte.",
    "Himmat tab hoti hai jab tum thak kar bhi ek aur kadam uthate ho.",
    "Aaj apne comfort zone se bas ek inch bahar niklo.",
    "Pehle thoda ghabrahat, phir thodi tasalli, phir thoda sa maza.",
    "Waqt aane par apne liye khade ho jao.",
    "Kal tum jo karne se darte the, aaj karo.",
    "Dil bhaari hai? Kisi se baat kar lo.",
    "Apne aap ko ek naya mauka do, naye andaaz mein.",
    "Himmat roz chhoti hoti hai, par har roz hoti hai.",
  ],
  discipline: [
    "Subah ki ek chhoti walk poore din ka mood badal deti hai.",
    "Paani peena bhi ek discipline hai. Abhi ek glass pi lo.",
    "Raat ko samay par sona sabse sasta productivity tip hai.",
    "Jo khaana tumhari body ko achha lagta hai, wahi chuno.",
    "Roz thoda stretch karo. Body ka bhi to kaam hai.",
    "Phone ko sone se aadha ghanta pehle door rakh do.",
    "Aaj ka walk miss ho gaya? Kal ka walk double mat karo, bas kar lo.",
    "Dinchariya wahi achhi jo tumhein thaka ke nahi, halka bana ke chale.",
    "Sone ka ek fix time, utne ka ek fix time. Bas.",
    "Healthy chuno, kabhi kabhi thoda mazedaar bhi.",
    "Ghar saaf rakhna dimaag saaf rakhne ka pehla kadam hai.",
    "Kal ke kapde aaj raat nikal lo.",
    "Waqt par khaana, waqt par sona, waqt par uthna: zindagi ka asli mantra.",
    "Kharcha likho, hisaab rakho. Aaj ka paisa kal ka sukoon hai.",
    "Aaj ka chhota budget kal ka bada aaram hai.",
    "Bills samay par bharo. Dimaag halka rehta hai.",
    "Kamra saaf, mann saaf. Ek chhoti jagah se shuru karo.",
    "Dawai ya vitamin lena na bhoolo. Chhoti cheezein bhi zaroori hain.",
    "Roz ka chhota sa hisaab, mahine ka bada sukoon.",
    "Apne routine ko pyaar se pakdo, zabardasti se nahi.",
    "Bina phone ke ek ghanta bitaana bhi abhyas hai.",
    "Subah ki chai ke saath aaj ka plan padh lo.",
    "Cheezein jagah par rakhne ki aadat se bahut waqt bachta hai.",
    "Aaj ka kaam kal par mat daalo, par aaj ka aaram kal tak mat taalo.",
    "Dheere dheere roz ka thoda sa. Ye hi sab kuch hai.",
    "Roz ek achhi aadat ko dohra do.",
    "Neend poori, paani poora, kaam poora: yahi tin cheezein sambhal lo.",
    "Jo kal tak aadat nahi tha, aaj shuru karoge toh ek din aadat ban jayega.",
    "Roz ka thoda wyayam, saal bhar ki taqat.",
    "Exercise ka ek chhota sa version bhi chalega.",
    "Aaj ke din ke liye ek niyam chuno aur use nibhao.",
  ],
  hope: [
    "Tumhari zindagi mein abhi bahut achhe pal baaki hain.",
    "Abhi jo dard hai, wo ek din ek yaad ban jayega.",
    "Dil halka hone mein waqt lagta hai, par hota zaroor hai.",
    "Kuch rishte dheere dheere sudharte hain. Dheeraj rakho.",
    "Aaj ki raat ke baad ek naya savera hai.",
    "Jo tumhein chhod gaye, unke jaane se kuch nayi jagah bani hai.",
    "Kai baar ek hi pal sab kuch badal deta hai.",
    "Dukh bhi ek mausam hai. Badal jaata hai.",
    "Kuch achhi cheezein hamesha raaste mein hoti hain.",
    "Phir hasoge. Phir khush hoge. Bas thoda waqt do.",
    "Dil ke zakhm dheere bharte hain, par bharte zaroor hain.",
    "Naye mausam mein naye phool khilte hain, tum bhi.",
    "Kal ek achha din ho sakta hai. Aaj bas jhel lo.",
    "Zindagi chhote chhote achhe pal se bani hai. Aaj ek dhoondh lo.",
    "Dost, parivaar, ek achhi baat: kabhi bhi kuch achha mil sakta hai.",
    "Aaj jo ruka hua hai, kal chalega.",
    "Har andheri raat mein kahin ek taara hota hai.",
    "Tumhein chhodna nahi hai. Aage badhna hai.",
    "Sab kuch kho dene ka dar sab kuch pa lene ki umeed se chhota hota hai.",
    "Waqt sab ka marham hai. Thoda sa intezaar.",
    "Kuch achha tumhari zindagi mein jald dastak dene wala hai.",
    "Kisi ka ek chhota sa message bhi din badal sakta hai.",
    "Tumhein jis cheez ki talaash hai, wo bhi tumhein dhoondh rahi hai.",
    "Pura saal kharab nahi hota. Aaj ka din bhi nahi.",
    "Abhi raat hai, par suraj nikalna wala hai.",
    "Zindagi mein ek achhi cheez bhi ho, toh umeed rakhne ka kaaran hai.",
    "Kuch bhi permanent nahi hota, na dard, na khushi.",
    "Kal, parso, ya agle mahine: ek achhi khabar zaroor aayegi.",
    "Dheere se muskurao. Zindagi tumhein dekh rahi hai.",
    "Naya din, naya mauka, nayi umeed.",
    "Har sunsaan raste ke aage ek bhari bazaar hota hai.",
  ],
  "self-worth": [
    "Tum bojh nahi, ek vardan ho kisi ke liye.",
    "Apne aap ko kam mat samjho. Tum kisi ke liye poori duniya ho.",
    "Tum jaise ho, waise hi pyaare ho.",
    "Tumhari bhaavnaayein sahi hain, chahe wo kabhi kabhi bhaari ho jaayein.",
    "Tum apni aankhon mein jaisa dikhte ho, usse behtar dikhte ho.",
    "Tumhari khamoshi bhi kuch kehti hai. Aur wo sunne laayak hai.",
    "Tum kisi ki saath ke laayak ho, aur sabse pehle apne saath ke.",
    "Apne aap ko thoda sa pyaar karo. Tumne bahut sahaa hai.",
    "Tumhari hasi mein kisi ka sukoon chhupa hai.",
    "Tum bas thak gaye ho, bure nahi ho.",
    "Apni qadar karo, taki doosre bhi karein.",
    "Tum ek achhe insaan ho. Aur ye baat tumhari galtiyon se bhi badi hai.",
    "Tum jo ho, wahi kaafi ho.",
    "Dil ko samjhao: main mehnat kar raha hoon aur wo kaafi hai.",
    "Tumhari zindagi ki kahani mein tum hi hero ho.",
    "Aaj apne aap ko ek tareef bolo.",
    "Tumhare saath bitaya hua samay kisi ke liye khaas hai.",
    "Tum apni raftaar mein sundar ho.",
    "Tum khud ko jitna kam samajhte ho, utne kam nahi ho.",
    "Apni feelings ko chhupana nahi, samajhna seekho.",
    "Tum kisi ki umeed ho, kisi ka sahara ho.",
    "Tumhari mehnat aur tumhari neeyat: dono sone jaisi hain.",
    "Apne aap par vishwas karo. Tum bahut kuch kar sakte ho.",
    "Aaj apni body ko thank you bolo, wo tumhare liye bahut kuch karti hai.",
    "Tumhein sab kuch perfect nahi karna. Bas tum bane rehna hai.",
    "Jo log tumhein samajhte hain, unki kadar karo, aur apni bhi.",
    "Tum kai logon ki muskurahat ki wajah ho.",
    "Tumne itna kuch seekha hai, aur abhi aur seekhoge.",
    "Apni zindagi ko jeena ek hunar hai, aur tum use seekh rahe ho.",
    "Tum ek hi ho, aur wahi sabse badi baat hai.",
    "Khud ko samjho, khud ko maano, khud ko pyaar do.",
  ],
  gratitude: [
    "Maa-papa ki ek awaaz bhi sukoon de deti hai. Aaj unse baat kar lo.",
    "Dost jo bina bataye samajh jaate hain: unhein yaad karo.",
    "Ghar ki chhat, apna bistar, apna kamra: sab nemat hai.",
    "Garam khaana aur ek achhi neend: aaj ke liye kaafi.",
    "Jo log tumhein har haal mein apnate hain, unka shukriya.",
    "Shukriya un sab ka jinhone tumhein bina mange pyaar diya.",
    "Aaj apne bhai-behen, ya kisi apne ko bata do ki wo kitna zaroori hai.",
    "Subah ki chai, sham ki hawa: bahut kuch muft mein milta hai.",
    "Un pal ka shukriya jo tumhein hasaa gaye.",
    "Apni body ka shukriya karo: wo roz tumhare liye kaam karti hai.",
    "Kisi ek ne tumhein samjha, wo bhi bahut hota hai.",
    "Khaana banane wale haath, kaam par bhejne wale dua: sabka shukriya.",
    "Aaj ek chhoti si cheez par dil se muskura do.",
    "Thanks un sab ko jo tumhare saath hain aur bina kuch kahe.",
    "Rishton ki garmi chai ki garmi se bhi achhi hoti hai.",
    "Tumhare paas jo bhi hai, usme kisi ki khushi chhupi ho sakti hai.",
    "Aaj raat khidki se chand ko shukriya bol do.",
    "Jo kal tak sapna tha, aaj shayad haqeeqat hai. Shukriya.",
    "Zindagi ke chhote chhote tohfe notice karna seekho.",
    "Pehle shukriya, phir shikayat. Aksar shikayat chhoti ho jaati hai.",
    "Aaj apne aas-paas ke kisi insaan ko sachche dil se thank you bolo.",
    "Dost ka ek message, ek meme, ek hasi: yahi to asli daulat hai.",
    "Un hathon ka shukriya jo tumhein chalna sikhate the.",
    "Apni zindagi ke achhe logon ko yaad karna ek pooja jaisa hai.",
    "Sahi samay par mila hua saath bhi nemat hai.",
    "Aaj kuch achha hua toh use ek baar jeekar dekho.",
    "Jisne tumhein kabhi sahara diya, use yaad rakhna.",
    "Ek achhe pal ko mehsoos karke dekho, kitna bada hota hai.",
    "Jo ghar tumhari raah dekhta hai, uska shukriya.",
    "Shukriya ka ek chhota sa lafz bhi rishta mazboot kar sakta hai.",
    "Aaj ke din ko ek hi shabd mein samet do: shukriya.",
  ],
  focus: [
    "Aaj bas ek kaam par dhyaan do. Baaki ko kal ke liye likh do.",
    "Khaate waqt phone door rakho. Khaane ka swaad alag hota hai.",
    "Kisi se baat karte waqt poora dhyaan do. Wo mehsoos karte hain.",
    "Aaj ke din ko teen hisson mein baanto: subah, dopahar, raat. Har hisse ka ek maqsad.",
    "Dhyaan ek tohfa hai. Use sambhal ke kharch karo.",
    "Ek kaam, ek saans, ek pal.",
    "Pehle apni body ko dhyaan do, phir kaam ko.",
    "Jab mann idhar udhar jaye, gently wapas laao.",
    "Aaj ka plan likh lo, aur uske bahar kam jao.",
    "Zaroori cheez ko bina shor ke karo.",
    "Padhne ya likhne se pehle ek glass paani pi lo.",
    "Kaam ke baad ka aaram bhi poore dhyaan se lo.",
    "Dhyaan kharab hone par chalo, thoda tehal ke aao.",
    "Ek achha kaam chhote kaamon ke dher se behtar hai.",
    "Phone ki jagah ek kitaab ke das panne.",
    "Sochna kam, karna zyada. Aaj ka motto.",
    "Dhyaan kharch nahi hota, badhta hai jab tum use istemal karte ho.",
    "Aaj subah ke pehle ghante ko apna maano.",
    "Ek kaam ka dhyaan hi sab se bada comfort hai.",
    "Aaj dhyaan ek hi jagah rakhne ka experiment karo.",
    "Shaam ko ek chhota sa review: aaj kya ho gaya?",
    "Mushkil kaam ko pehle karo, aasaan ko baad mein.",
    "Kaam shuru hone se pehle ek line likho: aaj ye khatam karna hai.",
    "Chhoti si cheez par poora dhyaan, bada sa sukoon.",
    "Poore din ka nahi, agle ghante ka plan banao.",
    "Dhyaan se kiya hua aadha kaam bhi bina dhyaan ke poore kaam se behtar hai.",
    "Do ghante ki hadbadi se ek ghante ka sukoon behtar hai.",
    "Pehle kaam ko samjho, phir shuru karo.",
    "Jo dikh raha hai wahi karo. Jo nahi dikh raha, wo baad mein.",
    "Dhyaan se suno, dhyaan se bolo, dhyaan se karo.",
    "Dhyaan ek aadat hai. Roz thoda abhyas.",
  ],
  "bounce-back": [
    "Rishte mein jhagda hua? Shaanti se baat karna hi pehla kadam hai.",
    "Kisi ne dil dukhaya? Zakhm bharne do, phir aage badho.",
    "Kisi se door ho gaye ho? Ek message ab bhi bheja ja sakta hai.",
    "Dukhi hona kamzori nahi, aage badhna taqat hai.",
    "Aaj jo toot gaya, usse kal naya banega.",
    "Pehle apne aap ko sambhalo, phir baaki sab.",
    "Ek bura hafta zindagi ka faisla nahi hota.",
    "Kabhi kabhi sirf bistar se uthna bhi badi jeet hoti hai.",
    "Khud ko bolo: main phir se shuru kar sakta hoon.",
    "Girna sharm ki baat nahi, wahin padhe rehna hai.",
    "Aaj ek chhoti si cheez karke dekho: pani pi lo, muh dho lo, bahar jao.",
    "Zakhm ke baad bhi tum utne hi pyaare ho.",
    "Dukh ke baad ki hasi sabse sachchi hoti hai.",
    "Rote ho toh ro lo, phir muh dho kar aage badho.",
    "Tumne pehle bhi bure din dekhe hain aur nikle ho.",
    "Aaj thoda kam karna, par band mat karna.",
    "Tum toote nahi ho, bas thak gaye ho.",
    "Jo kal tak asambhav lagta tha, wo aaj sambhav hai.",
    "Dil toota? Dil jud jaata hai, bas waqt lagta hai.",
    "Aaj ek chhoti jeet: bistar theek karo.",
    "Naye din ko mauka do, pichhle din ko chhod do.",
    "Wapas aao. Kisi ko hisaab nahi dena.",
    "Jab tak saans hai, shuruaat hai.",
    "Tumhein kisi se behtar nahi hona, bas kal ke tum se behtar hona hai.",
    "Aaj ek aur din jee liya. Ye hi jeet hai.",
    "Girne ke baad uthne wale ki kahani sabse achhi hoti hai.",
    "Zindagi ek second chance hamesha deti hai.",
    "Himmat nahi hai? Toh sirf ek chhoti si cheez karo.",
    "Gam ke baad ki chai ka alag hi swaad hota hai.",
    "Sambhal gaye ho pehle, sambhal jaoge phir se.",
    "Dil se maaf karo aur aage chalo.",
  ],
};

export const HI3 = build("hi3", ROWS);
