import { build, type QuoteRows } from "./types";

/** Hinglish, part 4: short, light, a little playful. Works on any mood. No authors. */
const ROWS: QuoteRows = {
  calm: [
    "Chill. Sab sambhal jayega.",
    "Ruk jao. Saans lo. Phir chalo.",
    "Aaj ki sabse badi planning: kuch nahi karna, aur wo bhi guilt-free.",
    "Mann ki ghanti thodi der silent par rakho.",
    "Aaj sirf ek kaam: halka rehna.",
    "Dheere dheere bhi pahunch jaate hain, aur raste ke nazare bhi dikhte hain.",
    "Jo hona hai ho jayega. Tum bas apna kaam dil se karo.",
    "Thoda sa break, thodi si hasi, thoda sa chai.",
    "Garam chai, thandi hawa, aur koi jaldi nahi.",
    "Duniya tez hai, tum apni chaal se chalo.",
    "Dimaag ko thoda 'airplane mode' do.",
    "Saans sabse sasta therapist hai.",
    "Tension ko chai ke saath uda do.",
    "Jab kuch na kar sako, toh bas rehna seekho.",
    "Aaj raat dimaag ko ghar chhod do.",
    "Sab theek hai. Bas thoda thoda karte hain.",
    "Phone nikalne se pehle ek lamba saans lo.",
    "Shor se door, apne aap ke paas.",
    "Sofa, chai, aur ek achha gaana. Aaj ka plan complete.",
    "Aaj kisi se jawab nahi dena. Bas rehna hai.",
    "Halka phulka din bhi ek din hota hai.",
    "Chinta ko thoda aaram do, usne bhi bahut kaam kiya hai.",
    "Sukoon shayad is saans mein hi hai.",
    "Pehle shaanti, phir faisla.",
    "Hum sab chal rahe hain, dheere ya tez. Chalna hi kaafi hai.",
    "Aaj dil ko naram rakho.",
    "Ek pal ruk kar dekho, sab kuch utna bhaari nahi hai.",
    "Hasi, chai aur sukoon: teeno ek saath.",
    "Is pal mein bas itna kaafi hai.",
    "Aaj kuch bhi 'urgent' nahi hai. Sach mein.",
    "Raat ko dimaag ko tala laga do.",
    "Peace ka matlab hai ki tum jaante ho ki sab kuch kal bhi ho sakta hai.",
    "Bas bahut hua, ab aaram.",
  ],
  courage: [
    "Dar ko pocket mein rakho, kadam aage badhao.",
    "Bas shuru kar do. Baaki raste mein sambhal jayega.",
    "Ek bar try toh banta hai.",
    "Aaj jo kaam mushkil lag raha hai, wahi sabse zaroori hai.",
    "Himmat dikhao, perfect mat bano.",
    "Haan bol do. Dekha jayega.",
    "Ek message ki doori hai. Bhej do.",
    "Tum jitna sochte ho, usse zyada kar sakte ho.",
    "Dar lagta hai? Matlab kuch important hai.",
    "Aaj thoda sa bold ho jao.",
    "Tum mushkil se bhi zyada mazboot ho.",
    "Pehla kadam, sabse bada kadam.",
    "Himmat ek tareeka hai chhote kadam uthane ka.",
    "Kal jo tum karne se dare, aaj kar ke dikha do.",
    "Aaj apne aap se vaada karo: main try karunga.",
    "Darr ka kya hai, wo toh har kisi ko lagta hai.",
    "Chalo, ek mauka aur khud ko do.",
    "Jo tumhein roke hue hai, wo ek aadat hai. Tod do.",
    "Tum ready ho, bas tumhein pata nahi.",
    "Baat karo, poochho, bolo. Chup rehne se kuch nahi badalta.",
    "Aaj ek naya kaam. Chhota sa hi sahi.",
    "Dil ki suno. Dimaag ko baad mein manao.",
    "Tum bahut aage aa chuke ho, pichhe dekho toh.",
    "Mushkil kaam ko ek dum se mat dekho; ek hisse se shuru karo.",
    "Dar ke saath bhi dosti ho sakti hai.",
    "Kam se kam ek baar toh bol do.",
    "Aaj kuch aisa karo ki raat ko khud par garv ho.",
    "Tum akele nahi ho, chahe tum aisa mehsoos karo.",
    "Zindagi un logon ko inaam deti hai jo ek aur baar koshish karte hain.",
    "Bina sochey nahi, thoda soch ke bhi chal do.",
    "Himmat aati hai chalne se, sochne se nahi.",
    "Ek kadam, phir ek aur.",
    "Darr ke aage jeet hai. Haan, sach mein.",
  ],
  discipline: [
    "Roz ka chhota sa kaam, ek din ka bada naam.",
    "Aaj ka kaam aaj. Kal ka kal.",
    "Bas das minute. Ho jayega.",
    "Aadat banane mein waqt lagta hai, lagne do.",
    "Dheere dheere, par roz.",
    "Alag baat hai kuch karna aur kuch karte rehna.",
    "Roz thoda, kabhi kabhi bahut.",
    "Chhoti si jeet aaj ki, bada safar kal ka.",
    "Subah ka kaam poore din ki thakaan bacha deta hai.",
    "Shuru kar do. Perfect baad mein.",
    "Aaj apni list ka pehla item nipta do.",
    "Ek tick, ek jeet.",
    "Jo roz hota hai wahi asal mein hota hai.",
    "Kal se nahi, aaj se. Chhote roop mein hi sahi.",
    "Ek chhota step roz, ek bada safar ek saal mein.",
    "Mehnat ke saath thoda dhairya, aur bas.",
    "Jab mann na ho, tab bhi ek chhota sa kar do.",
    "Aaj ka plan chhota rakho, par nibhao.",
    "Kaam chhota ho ya bada, roz ho toh bada ban jata hai.",
    "Aadat ban gayi toh sab aasaan.",
    "Jaisa roz karte ho, waisa hi ban jaate ho.",
    "Aaj apne aap se ek vaada nibhao.",
    "Subah ki chai ke saath aaj ka pehla kaam.",
    "Itna hi karo jitna roz kar sako.",
    "Likhne se kaam shuru ho jaata hai.",
    "Shuruaat chhoti ho toh bhi shuruaat hai.",
    "Aaj apne aap ko niraash mat karo.",
    "Ek ek karke sab ho jayega.",
    "Aaj ka kaam poora ho toh raat ko neend achhi aati hai.",
    "Jo kuch bhi ho, aaj apna sabse chhota version kar do.",
    "Mehnat ek aisa nivesh hai jo kabhi doobta nahi.",
    "Bas lagatar. Itna hi.",
    "Aaj ka din bhi ginti mein aata hai.",
  ],
  hope: [
    "Sab theek hoga. Bas thoda sa waqt.",
    "Achhe din aane wale hain, bas rasta thoda lamba hai.",
    "Kal ke baare mein soch ke muskura do.",
    "Aaj ka din bura hai, par har din aisa nahi hota.",
    "Subah hamesha aati hai.",
    "Kuch bhi ho sakta hai, aur wo achha bhi ho sakta hai.",
    "Aaj ek chhoti si umeed rakh lo jeb mein.",
    "Waqt badalta hai, tum bhi badloge.",
    "Jo gaya wo gaya, jo aayega wo behtar hoga.",
    "Dekhna, ek din tum yeh sab yaad karke hasoge.",
    "Rukne ka matlab khatam hona nahi hai.",
    "Aaj ek naya mauka hai, use pakad lo.",
    "Umeed ek chhoti si roshni hai, par kaafi hai.",
    "Aane wala kal tumhare liye kuch achha laaya hoga.",
    "Dheere dheere sab apni jagah par aa jaata hai.",
    "Tum jahan ho, wahan se rasta nikalta hai.",
    "Bura waqt bhi ek din thak jaata hai.",
    "Naye din ki nayi shuruaat.",
    "Pata nahi kab, par kuch achha zaroor hoga.",
    "Abhi ke liye itna kaafi hai ki tum yahan ho.",
    "Mushkil daur chhota hota hai, tumhari kahani lambi hai.",
    "Aasmaan saaf hone mein waqt lagta hai.",
    "Aane wale din tumhare apne hain.",
    "Phir se khilne ka mausam aayega.",
    "Kal ki sunehri subah tumhara intezaar kar rahi hai.",
    "Tum jitna sochte ho, haalat utni buri nahi hai.",
    "Har din ek naya panna hai.",
    "Aaj nahi toh kal, khushi aayegi.",
    "Dil se maango, aur dil se mehnat karo.",
    "Dhoop nikal rahi hai, bas thoda der se.",
    "Kuch din ke baad ye sab theek lagega.",
    "Achhe waqt ka intezaar karo, par achha banne ka kaam mat roko.",
    "Jaisa bhi aaj ka din ho, kal ek naya din hai.",
  ],
  "self-worth": [
    "Tum kaafi ho. Bas, itna hi.",
    "Tum special ho, bina kuch kiye bhi.",
    "Apne aap ko pyaar karna sikho, wahi sabse zaroori hai.",
    "Tum jaise ho, waisa hi bahut achha hai.",
    "Aaj apne aap ko ek shabaash bol do.",
    "Tum kisi se kam nahi.",
    "Tumhari value tumhare mood se nahi badalti.",
    "Tum ek insaan ho, aur wahi bahut hai.",
    "Aaj tumne jo bhi kiya, wo kaafi tha.",
    "Tumhare saath rehna kisi ke liye ek tohfa hai.",
    "Khud ko samjho, khud ko maaf karo.",
    "Tumhari mehnat tumhari pehchaan hai.",
    "Tum apni kahani ke hero ho.",
    "Apne aap par yakeen karna seekho.",
    "Tumhein har baar perfect nahi hona. Bas tum hona hai.",
    "Aaj ki thakaan bhi tumhari mehnat ka saboot hai.",
    "Tum kam nahi, bas thak gaye ho.",
    "Tumhare hone se farq padta hai.",
    "Aaj thoda sa khud ko pamper karo.",
    "Tumhari muskurahat kisi ka din achha kar sakti hai.",
    "Apni qadar karo, tum bahut qeemti ho.",
    "Tum kisi ke liye bahut khaas ho.",
    "Tum kai logon ki duaon mein ho.",
    "Tumhara naam sunke kisi ke chehre par muskaan aati hai.",
    "Khud ko bhi ek mauka do, jaise doosron ko dete ho.",
    "Tum jitne ho, utne hi asli ho.",
    "Tum apni jagah par bilkul sahi ho.",
    "Tum ek lambe safar par ho aur tumne achha kiya hai.",
    "Tum waise hi khoobsurat ho jaise ho.",
    "Tumhari zindagi ke liye tum hi sabse zaroori ho.",
    "Tumne itna kuch kiya hai, ab ek pal rukkar khud ko dekho.",
    "Aaj ke din tum apne aap ke dost bano.",
    "Tum waqai achhe insaan ho.",
  ],
  gratitude: [
    "Shukriya aaj ke liye.",
    "Ek chhoti si cheez ke liye shukriya bol do.",
    "Jo mila usme khush raho, jo nahi mila usme seekho.",
    "Aaj ke din ko ek shukriya do.",
    "Chai, dost, aur ek achha gaana: aur kya chahiye?",
    "Muskurao. Aaj bhi kuch achha hai.",
    "Jisne tumhein muskurana sikhaya, usse yaad karo.",
    "Dil se shukriya, bina kisi shart ke.",
    "Aaj jo hai wo kaafi hai.",
    "Aaj ek aisa kaam karo jis par kal shukriya mehsoos ho.",
    "Mil gaya toh shukriya, nahi mila toh bhi shukriya.",
    "Ek achha pal, ek achhi yaad, ek shukriya.",
    "Jo log tumhein samajhte hain, wo khazana hain.",
    "Garam khaana, thandi hawa: shukriya.",
    "Shukriya karna dil ko halka karta hai.",
    "Aaj dil se thank you bolna mat bhoolna.",
    "Khushi chhoti cheezon mein bhi hoti hai.",
    "Sone se pehle ek achhi baat yaad karo.",
    "Un sabko shukriya jo tumhare saath hain.",
    "Zindagi ne diya bahut kuch hai, bas dekhne ki der hai.",
    "Subah ki pehli kiran ka bhi shukriya.",
    "Ek achha din bhi nemat hai, ek ajeeb din bhi sabak.",
    "Aaj tumhein koi yaad kar raha hoga. Shukriya unka.",
    "Achhi sehat ka shukriya karo, wo sabse badi daulat hai.",
    "Shukriya, un sab ke liye jo hota hai bina kisi ke dekhe.",
    "Dil se muskurao, jo hai usme khushi dhundho.",
    "Aaj ek chhoti si kaamyabi ke liye bhi shukriya.",
    "Hum sab ke paas kuch na kuch hai jiske liye shukriya kar sakte hain.",
    "Aaj ka din bhi ek nemat hai.",
    "Shukriya, ki tum aaj bhi yahan ho.",
    "Dua mein shukriya sabse pehle ata hai.",
    "Aaj ek shukriya likho, aur kal ek aur.",
    "Chhoti baat par bhi dil se thank you.",
  ],
  focus: [
    "Ek time par ek kaam. Itna hi.",
    "Phone down, kaam up.",
    "Pehle kaam, phir scroll.",
    "Dhyaan ek hi jagah, ek hi samay.",
    "Pehle sabse zaroori kaam. Baaki sab line mein.",
    "Bas panch minute focus. Fir dekhte hain.",
    "Kaam shuru karo, dhyaan khud aa jayega.",
    "Dhyaan dene mein hi asli mazaa hai.",
    "Ek kaam, poora mann.",
    "Jo kaam abhi zaroori hai, uski taraf dekho.",
    "Mind ko bolo: ab bas yeh ek kaam.",
    "Shor kam, kaam zyada.",
    "Ek goal chuno, uske peeche lag jao.",
    "Aaj ka focus: ek chhoti si jeet.",
    "Distractions ko 'baad mein' ke dabbe mein daal do.",
    "Likh lo kya karna hai, phir karo.",
    "Ek poora ghanta, sirf ek kaam ke liye.",
    "Dhyaan ek rassi hai: use mazbooti se pakdo.",
    "Mushkil kaam ko timer ke saath karo.",
    "Pehle shuru karo, phir sochna.",
    "Kaam ko dikhne wali jagah rakho.",
    "Kam cheezon par zyada dhyaan.",
    "Aaj ek kaam ko dil se karo.",
    "Dhyaan se kiya gaya chhota kaam bhi bada asar karta hai.",
    "Jo zaroori hai wo pehle, jo chamakdar hai wo baad mein.",
    "Ek ek ghanta jeet lo, poora din apna ho jayega.",
    "Dhyaan bata do apne aap ko: ye kaam aaj khatam hoga.",
    "Dimaag mein sirf ek kaam, bas.",
    "Pehle chhote kaam, phir bada kaam. Ya ulta, jo tumhein sahi lage.",
    "Kaam ko seedha dekho, bahaane ko ulta.",
    "Dhyaan do aur dekho kitna ho jata hai.",
    "Pehle ye ek kaam. Phir agla.",
    "Dhyaan wapas laao, bina gussa kiye.",
  ],
  "bounce-back": [
    "Gir gaye? Uth jao. Dhool jhaado. Chalo.",
    "Ek aur try. Is baar thoda alag.",
    "Haar ke baad bhi tum wahi ho: mazboot.",
    "Aaj ka din gaya, kal naya.",
    "Galti ho gayi toh kya hua? Seekh liya na.",
    "Phir se shuru karna kabhi der nahi hoti.",
    "Girna ek baar, uthna do baar.",
    "Rukne se behtar hai ki dheere chalo.",
    "Aaj kuch bhi nahi hua toh kal kuch hoga.",
    "Wapas aana bhi ek jeet hai.",
    "Thoda break lo, phir aao.",
    "Tum haare nahi ho, bas thak gaye ho.",
    "Naye din ka naya plan.",
    "Mushkil din bhi guzar jaate hain.",
    "Phir se chalo. Ek kadam.",
    "Kal ke tum ko chhodo, aaj ke tum ko chuno.",
    "Dobara khade ho jao, is baar ek kadam aage.",
    "Sab kuch toot gaya? Phir se jodo, alag tareeke se.",
    "Bura waqt tumhein khatam nahi karta, mazboot karta hai.",
    "Girne wala hi chalna seekhta hai.",
    "Thodi der ro lo. Phir uth jao.",
    "Jo hua so hua. Ab aage.",
    "Tumne sambhala hai pehle bhi, aaj bhi sambhal loge.",
    "Haar maan lena aur ruk jana alag hota hai. Tum bas ruke ho.",
    "Aaj dil bhaari hai? Kal halka hoga.",
    "Dubara try karna sabse achha badla hai.",
    "Himmat nahi chhodni, bas rasta badalna hai.",
    "Subah ho gayi, ab nayi shuruaat.",
    "Girte raho, uthte raho. Safar chalta rahega.",
    "Ek aur din, ek aur mauka.",
    "Ruko mat, bas dheere ho jao.",
    "Aaj ka haal kal ka itihaas ban jayega.",
    "Zindagi ek aur mauka hamesha deti hai.",
  ],
};

export const HI4 = build("hi4", ROWS);
